=== gentoo/gentoo/metadata/dtd/glsa.dtd
<!-- $Header: /var/cvsroot/gentoo/xml/htdocs/dtd/glsa.dtd,v 1.17 2008/04/04 17:04:39 neysx Exp $ -->
<!ELEMENT glsa  (title,synopsis,product,announced,revised,bug*,access?,affected,background?,description,impact,workaround,resolution,references,license?,metadata*)>
<!ATTLIST glsa  id  CDATA   #REQUIRED>

<!-- 
    Element:      title
    Description:  Provides a 4-5 word description about the advisory 
    Example:      <title>Buffer overflow vulnerability found in openssl-0.9.5</title> 
-->
<!ELEMENT title  (#PCDATA)>

<!-- 
    Element:      synopsis
    Description:  Small, to-the-point description about the GLSA

    Example:  <synopsis>
                  rsync has an exploitable buffer overflow that can lead to
                  remote compromise
              </synopsis>
-->
<!ELEMENT synopsis   (#PCDATA)>

<!-- 
    Element:      product
    Description:  Defines what type of security announcement this is.
    
                  Valid types are:
                  - ebuild         A Portage-provided ebuild has a security 
                                   issue
                  - informational  This GLSA is purely informational, no Gentoo
                                   system is affected
                  - infrastructure The security issue involves the Gentoo 
                                   infrastructure
    
                  The text contains one keyword that defines the issue.
                  Note: All type values but 'ebuild' are considered deprecated.
     
    Example: <product type="ebuild">openssl</product>
    Example: <product type="infrastructure">rsync mirror</product>
-->
<!ELEMENT product   (#PCDATA)>
<!ATTLIST product   type    (ebuild|infrastructure|informational) #REQUIRED>

<!--
    Element:      announced
    Description:  Date when the advisory is publicised
                  The format must be "YYYY-mm-dd"

    Example: <announced>2003-11-20</announced>
-->
<!ELEMENT announced (#PCDATA)>

<!--
    Element:      revised
    Description:  Last revision date of the GLSA
    Attribute:    @count: number of revisions
    
    Example: <revised count="02">2003-11-20</revised>
-->
<!ELEMENT revised (#PCDATA)>
<!ATTLIST revised count CDATA "01">

<!--
    Element:      bug
    Description:  Number of the bug on bugs.gentoo.org, if any
    Occurrence:    The bug element can occur 0, 1 or more times

    Example: <bug>34200</bug>
-->
<!ELEMENT bug       (#PCDATA)>

<!--
    Element:      access
    Description:  Type of access necessary to exploit the security issue
                  This element should only be used when product@type = 'ebuild'
    Occurrence:    The access element can occur 0 or 1 time
    
    Example: <access>Remote</access>
-->
<!ELEMENT access    (#PCDATA)>

<!--
    Element:      affected
    Description:  Describe what the affected subjects are.
    
                  If product@type = 'ebuild', the child elements are 'package'
                  If product@type = 'portage', the child elements are 'package'
                  If product@type = 'infrastructure', the child elements are 
                  'service'

-->
<!ELEMENT affected  (package*|service*)>

<!--
    Element:      package
    Description:  Provide all necessary information regarded the affected 
                  packages. It also contains information about the affected 
                  architectures, if automatic updates can be done and the update

                  The "update" attribute contains the path to the non-vulnerable
                  version of the package

                  The "auto" attribute contains either "yes" or "no" and tells 
                  Portage that the package can be updated automatically (to be 
                  implemented) without further user interaction

                  The "arch" attribute contains either the architecture (as used
                  by ACCEPT_KEYWORDS) or the "*" value (in case all 
                  architectures are affected)

    Occurrence:   The package element can occur 0, 1 or more times
    Example:      <package name="dev-libs/openssl" auto="yes" arch="*">
                    <vulnerable range="lt">0.9.6k</vulnerable>
                    <unaffected range="gt">0.9.6k</unaffected>
                  </package>
-->
<!ELEMENT package (vulnerable|unaffected)*>
<!ATTLIST package name      CDATA           #REQUIRED
                  auto      (yes|no)    #REQUIRED
                  arch      CDATA           #REQUIRED>

<!--
    Element:      vulnerable
    Description:  Version of the vulnerable package. Can be a range too
-->
<!ELEMENT vulnerable (#PCDATA)>
<!ATTLIST vulnerable range      (le|lt|eq|gt|ge|rlt|rle|rgt|rge)      #REQUIRED
                     slot       CDATA                 "*">

<!--
    Element:      unaffected
    Description:  Version of the fixed (or unaffected) package. In case the 
                  package is superseded by another package, you need to
                  define that package using the "name" attribute.

                  The r* range information is revision-specific. For instance, 
                  rge foo-1.2.3-r4  ==  >=foo-1.2.3-r4 && <foo-1.2.4

    Example:
                  <unaffected range="gt" name="foobar">2.0.0</unaffected>
-->
<!ELEMENT unaffected (#PCDATA)>
<!ATTLIST unaffected range      (le|lt|eq|gt|ge|rlt|rle|rgt|rge)      #REQUIRED
                     slot       CDATA                 "*"
                     name       CDATA                 #IMPLIED>

<!--
    Element:      service
    Description:  Provide information about the Gentoo services that are
                  affected by the security advisory. Portage must be able
                  to parse this information to make decisions (for instance, 
                  ignore an rsync server or a certain distfiles mirror).

                  The type attribute can be one of "rsync", "web", "mirror".

                  The fixed attribute (denoting if the problem has been solved)
                  can be one of "yes" or "no". If not used, the default value is
                  "no".
                  
    Occurrence:   The service element can occur 0, 1 or more times
    Example: <service type="rsync">rsync://rsync.someserver.tld/gentoo-portage</service>
-->
<!ELEMENT service (#PCDATA)>
<!ATTLIST service type (rsync|web|mirror) #REQUIRED
                  fixed (yes|no)          #IMPLIED>

<!--
    Element:      uri
    Description:  Link to the organisation involved in releasing the advisory
    Occurrence:   The uri element can occur 0, 1 or more times

    Example:      <uri link="http://www.cert.org">CERT</uri>
-->
<!ELEMENT uri       (#PCDATA)>
<!ATTLIST uri     link  CDATA   #IMPLIED>

<!--
    Element:      mail
    Description:  Mail address of the people involved in releasing the advisory
    Occurrence:   The mail element can occur 0, 1 or more times

    Example:      <mail link="some@person.com">Some Person</mail>
-->
<!ELEMENT mail      (#PCDATA)>
<!ATTLIST mail    link  CDATA   #REQUIRED>

<!--
    Element:      p
    Description:  Plain text
    Occurrence:   The "p" element can occur 0, 1 or more times and can contain
                  links or addresses

    Example:      <p>Please update your system</p>
-->
<!ELEMENT p (#PCDATA|mail|uri|b|i|br)*>

<!--
    Element:      code
    Description:  The code element contains text that should preserve whitespace
                  and is therefore useful for code listings or commands

    Example:      <code>emerge sync</code>
-->
<!ELEMENT code (#PCDATA)>

<!--
    Element:      background
    Description:  Provides a background of the affected package(s)/service(s)
                  The background element contains only "<p>"s in which the text 
                  is placed

-->
<!ELEMENT background  (p|ul|ol)*>

<!--
    Element:      description
    Description:  Provides a description about the security issue
                  The description element contains only "<p>"s.
-->
<!ELEMENT description (p|ul|ol|code)*>

<!--
    Element:      impact
    Description:  Provides information about the impact that the security issue 
                  can have

                  The "impact" element contains only "<p>"s.

                  The type element gives a short term, such as 
                  "Denial of Service", "Buffer Overflow", ...

-->
<!ELEMENT impact    (p|ul|ol)*>
<!ATTLIST impact    type    CDATA   #REQUIRED>

<!--
    Element:      workaround
    Description:  Provides information about how the security issue can be 
                  (temporarily) resolved through a work-around

                  The "workaround" element contains only "<p>"s and "<code>"s.
-->
<!ELEMENT workaround    (p|code|ul|ol)*>

<!--
    Element:      resolution
    Description:  Provides information about how the security issue can be 
                  resolved.

                  The "resolution" element contains only "<p>"s and "<code>"s.
-->
<!ELEMENT resolution  (p|code|ul|ol)*>

<!--
    Element:      references
    Description:  Provides links to resources / references available online.
                  
                  The "reference" element contains only "<uri>"s.
-->
<!ELEMENT references    (uri*)>

<!--
    Element:      ul
    Description:  Add an unnumbered listing; can only contain <li>'s
-->
<!ELEMENT ul            (li*)>

<!--
    Element:      ol
    Description:  Add a numbered listing; can only contain <li>'s
-->
<!ELEMENT ol            (li*)>

<!--
    Element:      li
    Description:  Element of a listing 
 
    Example:    <ul>
                  <li>This is element one</li>
                  <li>This is a second element</li>
                </ul>
-->
<!ELEMENT li            (#PCDATA)>

<!--
    Element:      b
    Description:  Bold text

    Example:    <b>this is bold</b>
-->
<!ELEMENT b             (#PCDATA)>

<!--
    Element:      i
    Description:  Input text (blue)

    Example:      The user has to type in <i>ls</i> to see.
-->
<!ELEMENT i             (#PCDATA)>

<!-- 
    Element:      br
    Description:  hard line break

    Example:      And then: <br/> 
                  KABLAM!
-->
<!ELEMENT br            (#PCDATA)>

<!-- 
    Element:      license
    Description:  Add license information

    Example:      <license/>
-->
<!ELEMENT license       (EMPTY)>

<!--
    Element:      metadata
    Description:  Metadata information for GLSAMaker

    Example:      <metadata tag="approved">Level 1</metadata>

    On request of plasmaroo, metadata can contain all elements again. 
-->
<!ELEMENT metadata  (#PCDATA|metadata)*>
<!ATTLIST metadata tag      CDATA #REQUIRED
                   revision CDATA #IMPLIED
                   author   CDATA #IMPLIED
                   timestamp CDATA #IMPLIED>

=== gentoo/gentoo/glsa-201503-10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE glsa SYSTEM "http://www.gentoo.org/dtd/glsa.dtd">
<glsa id="201503-10">
  <title>Python: Multiple vulnerabilities</title>
  <synopsis>Multiple vulnerabilities have been found in Python, the worst of
    which could lead to arbitrary code execution.
  </synopsis>
  <product type="ebuild">python</product>
  <announced>March 18, 2015</announced>
  <revised>March 18, 2015: 1</revised>
  <bug>495224</bug>
  <bug>500518</bug>
  <bug>505068</bug>
  <bug>506084</bug>
  <bug>514686</bug>
  <bug>523792</bug>
  <bug>532232</bug>
  <access>local, remote</access>
  <affected>
    <package name="dev-lang/python" auto="yes" arch="*">
      <unaffected range="ge">3.3.5-r1</unaffected>
      <unaffected range="rge">2.7.9-r1</unaffected>
      <vulnerable range="lt">3.3.5-r1</vulnerable>
    </package>
  </affected>
  <background>
    <p>Python is an interpreted, interactive, object-oriented programming
      language.
    </p>
  </background>
  <description>
    <p>Multiple vulnerabilities have been discovered in Python. Please review
      the CVE identifiers referenced below for details.
    </p>
  </description>
  <impact type="normal">
    <p>A context-dependent attacker may be able to execute arbitrary code or
      cause a Denial of Service condition.
    </p>
  </impact>
  <workaround>
    <p>There is no known workaround at this time.</p>
  </workaround>
  <resolution>
    <p>All Python 3.3 users should upgrade to the latest version:</p>
    
    <code>
      # emerge --sync
      # emerge --ask --oneshot --verbose "&gt;=dev-lang/python-3.3.5-r1"
    </code>
    
    <p>All Python 2.7 users should upgrade to the latest version:</p>
    
    <code>
      # emerge --sync
      # emerge --ask --oneshot --verbose "&gt;=dev-lang/python-2.7.9-r1"
    </code>
  </resolution>
  <references>
    <uri link="http://nvd.nist.gov/nvd.cfm?cvename=CVE-2013-1752">CVE-2013-1752</uri>
    <uri link="http://nvd.nist.gov/nvd.cfm?cvename=CVE-2013-7338">CVE-2013-7338</uri>
    <uri link="http://nvd.nist.gov/nvd.cfm?cvename=CVE-2014-1912">CVE-2014-1912</uri>
    <uri link="http://nvd.nist.gov/nvd.cfm?cvename=CVE-2014-2667">CVE-2014-2667</uri>
    <uri link="http://nvd.nist.gov/nvd.cfm?cvename=CVE-2014-4616">CVE-2014-4616</uri>
    <uri link="http://nvd.nist.gov/nvd.cfm?cvename=CVE-2014-7185">CVE-2014-7185</uri>
    <uri link="http://nvd.nist.gov/nvd.cfm?cvename=CVE-2014-9365">CVE-2014-9365</uri>
  </references>
  <metadata tag="requester" timestamp="Mon, 18 Aug 2014 20:14:36 +0000">K_F</metadata>
  <metadata tag="submitter" timestamp="Wed, 18 Mar 2015 22:30:27 +0000">
    BlueKnight
  </metadata>
</glsa>

=== gentoo/gentoo/metadata/glsa/glsa-200607-02.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE glsa SYSTEM "http://www.gentoo.org/dtd/glsa.dtd">

<glsa id="200607-02">
  <title>FreeType: Multiple integer overflows</title>
  <synopsis>
    Multiple remotely exploitable buffer overflows have been discovered in
    FreeType, resulting in the execution of arbitrary code.
  </synopsis>
  <product type="ebuild">FreeType</product>
  <announced>July 09, 2006</announced>
  <revised>September 03, 2006: 02</revised>
  <bug>124828</bug>
  <access>remote</access>
  <affected>
    <package name="media-libs/freetype" auto="yes" arch="*">
      <unaffected range="ge">2.1.10-r2</unaffected>
      <unaffected range="lt">2.0</unaffected>
      <vulnerable range="lt">2.1.10-r2</vulnerable>
    </package>
  </affected>
  <background>
    <p>
    FreeType is a portable font engine.
    </p>
  </background>
  <description>
    <p>
    Multiple integer overflows exist in a variety of files (bdf/bdflib.c,
    sfnt/ttcmap.c, cff/cffgload.c, base/ftmac.c).
    </p>
  </description>
  <impact type="normal">
    <p>
    A remote attacker could exploit these buffer overflows by enticing a
    user to load a specially crafted font, which could result in the
    execution of arbitrary code.
    </p>
  </impact>
  <workaround>
    <p>
    There is no known workaround at this time.
    </p>
  </workaround>
  <resolution>
    <p>
    All FreeType users should upgrade to the latest stable version:
    </p>
    <code>
    # emerge --sync
    # emerge --ask --oneshot --verbose &quot;&gt;=media-libs/freetype-2.1.10-r2&quot;</code>
  </resolution>
  <references>
    <uri link="http://www.cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2006-1861">CVE-2006-1861</uri>
  </references>
  <metadata tag="requester" timestamp="Tue, 04 Jul 2006 13:58:56 +0000">
    falco
  </metadata>
  <metadata tag="submitter" timestamp="Tue, 04 Jul 2006 15:44:57 +0000">
    hlieberman
  </metadata>
  <metadata tag="bugReady" timestamp="Wed, 05 Jul 2006 16:43:48 +0000">
    falco
  </metadata>
</glsa>

=== gentoo/gentoo/metadata/glsa/glsa-200903-09.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE glsa SYSTEM "http://www.gentoo.org/dtd/glsa.dtd">

<glsa id="200903-09">
  <title>OpenTTD: Execution of arbitrary code</title>
  <synopsis>
    Multiple buffer overflows in OpenTTD might allow for the execution of
    arbitrary code in the server.
  </synopsis>
  <product type="ebuild">openttd</product>
  <announced>March 07, 2009</announced>
  <revised>March 07, 2009: 01</revised>
  <bug>233929</bug>
  <access>remote</access>
  <affected>
    <package name="games-simulation/openttd" auto="yes" arch="*">
      <unaffected range="ge">0.6.3</unaffected>
      <vulnerable range="lt">0.6.3</vulnerable>
    </package>
  </affected>
  <background>
    <p>
    OpenTTD is a clone of Transport Tycoon Deluxe.
    </p>
  </background>
  <description>
    <p>
    Multiple buffer overflows have been reported in OpenTTD, when storing
    long for client names (CVE-2008-3547), in the TruncateString function
    in src/gfx.cpp (CVE-2008-3576) and in src/openttd.cpp when processing a
    large filename supplied to the "-g" parameter in the ttd_main function
    (CVE-2008-3577).
    </p>
  </description>
  <impact type="high">
    <p>
    An authenticated attacker could exploit these vulnerabilities to
    execute arbitrary code with the privileges of the OpenTTD server.
    </p>
  </impact>
  <workaround>
    <p>
    There is no known workaround at this time.
    </p>
  </workaround>
  <resolution>
    <p>
    All OpenTTD users should upgrade to the latest version:
    </p>
    <code>
    # emerge --sync
    # emerge --ask --oneshot --verbose &quot;&gt;=games-simulation/openttd-0.6.3&quot;</code>
  </resolution>
  <references>
    <uri link="http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2008-3547">CVE-2008-3547</uri>
    <uri link="http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2008-3576">CVE-2008-3576</uri>
    <uri link="http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2008-3577">CVE-2008-3577</uri>
  </references>
  <metadata tag="requester" timestamp="Thu, 12 Feb 2009 19:13:14 +0000">
    rbu
  </metadata>
  <metadata tag="submitter" timestamp="Fri, 13 Feb 2009 15:07:08 +0000">
    rbu
  </metadata>
  <metadata tag="bugReady" timestamp="Fri, 13 Feb 2009 15:08:05 +0000">
    rbu
  </metadata>
</glsa>

=== gentoo/gentoo/metadata/glsa/glsa-201611-13.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE glsa SYSTEM "http://www.gentoo.org/dtd/glsa.dtd">
<glsa id="201611-13">
  <title>MongoDB: Denial of Service</title>
  <synopsis>A vulnerability in MongoDB can lead to a Denial of Service
    condition.
  </synopsis>
  <product type="ebuild">mongodb</product>
  <announced>November 20, 2016</announced>
  <revised>November 20, 2016: 1</revised>
  <bug>542880</bug>
  <access>remote</access>
  <affected>
    <package name="dev-db/mongodb" auto="yes" arch="*">
      <unaffected range="ge">2.4.13</unaffected>
      <vulnerable range="lt">2.4.13</vulnerable>
    </package>
  </affected>
  <background>
    <p>MongoDB (from “humongous”) is a scalable, high-performance, open
      source, schema-free, document-oriented database.
    </p>
  </background>
  <description>
    <p>MongoDB’s ‘mongod’ server fails to validate some cases of
      malformed BSON.
    </p>
  </description>
  <impact type="normal">
    <p>A remote attacker could send a specially crafted BSON request possibly
      resulting in a Denial of Service condition.
    </p>
  </impact>
  <workaround>
    <p>There is no known workaround at this time.</p>
  </workaround>
  <resolution>
    <p>All MongoDB users should upgrade to the latest version:</p>
    
    <code>
      # emerge --sync
      # emerge --ask --oneshot --verbose "&gt;=dev-db/mongodb-2.4.13"
    </code>
  </resolution>
  <references>
    <uri link="http://nvd.nist.gov/nvd.cfm?cvename=CVE-2015-1609">CVE-2015-1609</uri>
  </references>
  <metadata tag="requester" timestamp="Mon, 11 May 2015 20:38:27 +0000">K_F</metadata>
  <metadata tag="submitter" timestamp="Sun, 20 Nov 2016 22:09:15 +0000">b-man</metadata>
</glsa>

=== gentoo/gentoo/metadata/glsa/glsa-200601-05.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE glsa SYSTEM "http://www.gentoo.org/dtd/glsa.dtd">

<glsa id="200601-05">
  <title>mod_auth_pgsql: Multiple format string vulnerabilities</title>
  <synopsis>
    Format string vulnerabilities in mod_auth_pgsql may lead to the execution
    of arbitrary code.
  </synopsis>
  <product type="ebuild">mod_auth_pgsql</product>
  <announced>January 10, 2006</announced>
  <revised>December 30, 2007: 03</revised>
  <bug>118096</bug>
  <access>remote</access>
  <affected>
    <package name="www-apache/mod_auth_pgsql" auto="yes" arch="*">
      <unaffected range="ge">2.0.3</unaffected>
      <unaffected range="lt">1.0.0</unaffected>
      <vulnerable range="lt">2.0.3</vulnerable>
    </package>
  </affected>
  <background>
    <p>
    mod_auth_pgsql is an Apache2 module that allows user authentication
    against a PostgreSQL database.
    </p>
  </background>
  <description>
    <p>
    The error logging functions of mod_auth_pgsql fail to validate certain
    strings before passing them to syslog, resulting in format string
    vulnerabilities.
    </p>
  </description>
  <impact type="high">
    <p>
    An unauthenticated remote attacker could exploit these vulnerabilities
    to execute arbitrary code with the rights of the user running the
    Apache2 server by sending specially crafted login names.
    </p>
  </impact>
  <workaround>
    <p>
    There is no known workaround at this time.
    </p>
  </workaround>
  <resolution>
    <p>
    All mod_auth_pgsql users should upgrade to the latest version:
    </p>
    <code>
    # emerge --sync
    # emerge --ask --oneshot --verbose &quot;&gt;=www-apache/mod_auth_pgsql-2.0.3&quot;</code>
  </resolution>
  <references>
    <uri link="http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2005-3656">CVE-2005-3656</uri>
    <uri link="http://www.frsirt.com/english/advisories/2006/0070">FrSIRT ADV-2006-0070</uri>
  </references>
  <metadata tag="requester" timestamp="Sun, 08 Jan 2006 17:42:51 +0000">
    DerCorny
  </metadata>
  <metadata tag="bugReady" timestamp="Sun, 08 Jan 2006 17:43:17 +0000">
    DerCorny
  </metadata>
  <metadata tag="submitter" timestamp="Mon, 09 Jan 2006 09:56:56 +0000">
    DerCorny
  </metadata>
</glsa>

=== gentoo/gentoo/metadata/glsa/glsa-201606-12.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE glsa SYSTEM "http://www.gentoo.org/dtd/glsa.dtd">
<glsa id="201606-12">
  <title>libssh and libssh2: Multiple vulnerabilities</title>
  <synopsis>Multiple vulnerabilities have been found in libssh and libssh2, the
    worst of which allows remote attackers to cause Denial of Service.
  </synopsis>
  <product type="ebuild"></product>
  <announced>June 26, 2016</announced>
  <revised>June 26, 2016: 1</revised>
  <bug>533366</bug>
  <bug>575474</bug>
  <bug>575484</bug>
  <access>remote</access>
  <affected>
    <package name="net-libs/libssh" auto="yes" arch="*">
      <unaffected range="ge">0.7.3</unaffected>
      <vulnerable range="lt">0.7.3</vulnerable>
    </package>
    <package name="net-libs/libssh2" auto="yes" arch="*">
      <unaffected range="ge">1.7.0</unaffected>
      <vulnerable range="lt">1.7.0</vulnerable>
    </package>
  </affected>
  <background>
    <p>libssh is a mulitplatform C library implementing the SSHv2 and SSHv1
      protocol on client and server side.
    </p>
  </background>
  <description>
    <p>libssh and libssh2 both have a bits/bytes confusion bug and generate an
      abnormaly short ephemeral secret for the diffie-hellman-group1 and
      diffie-hellman-group14 key exchange methods. The resulting secret is 128
      bits long, instead of the recommended sizes of 1024 and 2048 bits
      respectively.
    </p>
    
    <p>Additionally, a double free on dangling pointers in initial key exchange
      packets within libssh could leave dangling pointers in the session crypto
      structures. It is possible to send a malicious kexinit package to
      eventually cause a server to do a double-free before this fix. This could
      be used for a Denial of Service attack.
    </p>
  </description>
  <impact type="normal">
    <p>Remote attackers may gain access to confidential information due to the
      short keysize generated by libssh and libssh2, or cause a Denial of
      Service condition.
    </p>
  </impact>
  <workaround>
    <p>There is no known workaround at this time.</p>
  </workaround>
  <resolution>
    <p>All libssh users should upgrade to the latest version:</p>
    
    <code>
      # emerge --sync
      # emerge --ask --oneshot --verbose "&gt;=net-libs/libssh-0.7.3"
    </code>
    
    <p>All libssh2 users should upgrade to the latest version:</p>
    
    <code>
      # emerge --sync
      # emerge --ask --oneshot --verbose "&gt;=net-libs/libssh2-1.7.0"
    </code>
  </resolution>
  <references>
    <uri link="http://nvd.nist.gov/nvd.cfm?cvename=CVE-2014-8132">CVE-2014-8132</uri>
    <uri link="http://nvd.nist.gov/nvd.cfm?cvename=CVE-2016-0739">CVE-2016-0739</uri>
    <uri link="http://nvd.nist.gov/nvd.cfm?cvename=CVE-2016-0787">CVE-2016-0787</uri>
  </references>
  <metadata tag="requester" timestamp="Tue, 30 Jun 2015 22:23:55 +0000">
    keytoaster
  </metadata>
  <metadata tag="submitter" timestamp="Sun, 26 Jun 2016 12:56:59 +0000">b-man</metadata>
</glsa>

=== gentoo/gentoo/glsa-200701-07.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE glsa SYSTEM "http://www.gentoo.org/dtd/glsa.dtd">
<glsa id="200701-07">
  <title>OpenOffice.org: EMF/WMF file handling vulnerabilities</title>
  <synopsis>
    A truncation error and integer overflows in the EMF/WMF file handling of
    OpenOffice.org could be exploited to execute arbitrary code.
  </synopsis>
  <product type="ebuild">openoffice</product>
  <announced>2007-01-12</announced>
  <revised count="01">2007-01-12</revised>
  <bug>159951</bug>
  <access>remote</access>
  <affected>
    <package name="app-office/openoffice-bin" auto="yes" arch="*">
      <unaffected range="ge">2.1.0</unaffected>
      <vulnerable range="lt">2.1.0</vulnerable>
    </package>
    <package name="app-office/openoffice" auto="yes" arch="*">
      <unaffected range="ge">2.0.4</unaffected>
      <vulnerable range="lt">2.0.4</vulnerable>
    </package>
  </affected>
  <background>
    <p>
    OpenOffice.org is an open source office productivity suite, including
    word processing, spreadsheet, presentation, drawing, data charting,
    formula editing, and file conversion facilities.
    </p>
  </background>
  <description>
    <p>
    John Heasman of NGSSoftware has discovered integer overflows in the
    EMR_POLYPOLYGON and EMR_POLYPOLYGON16 processing and an error within
    the handling of META_ESCAPE records.
    </p>
  </description>
  <impact type="normal">
    <p>
    An attacker could exploit these vulnerabilities to cause heap overflows
    and potentially execute arbitrary code with the privileges of the user
    running OpenOffice.org by enticing the user to open a document
    containing a malicious WMF/EMF file.
    </p>
  </impact>
  <workaround>
    <p>
    There is no known workaround known at this time.
    </p>
  </workaround>
  <resolution>
    <p>
    All OpenOffice.org binary users should update to version 2.1.0 or
    later:
    </p>
    <code>
    # emerge --sync
    # emerge --ask --oneshot --verbose "&gt;=app-office/openoffice-bin-2.1.0"</code>
    <p>
    All OpenOffice.org users should update to version 2.0.4 or later:
    </p>
    <code>
    # emerge --sync
    # emerge --ask --oneshot --verbose "&gt;=app-office/openoffice-2.0.4"</code>
  </resolution>
  <references>
    <uri link="https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2006-5870">CVE-2006-5870</uri>
  </references>
  <metadata tag="requester" timestamp="2007-01-09T18:48:36Z">
    DerCorny
  </metadata>
  <metadata tag="submitter" timestamp="2007-01-09T19:06:14Z">
    DerCorny
  </metadata>
  <metadata tag="bugReady" timestamp="2007-01-12T12:16:11Z">
    falco
  </metadata>
</glsa>
