=== gentoo/gentoo/metadata/dtd/glsa.dtd
<!-- $Header: /var/cvsroot/gentoo/xml/htdocs/dtd/glsa.dtd,v 1.17 2008/04/04 17:04:39 neysx Exp $ -->
<!ELEMENT glsa  (title,synopsis,product,announced,revised,bug*,access?,affected,background?,description,impact,workaround,resolution,references,license?,metadata*)>
<!ATTLIST glsa  id  CDATA   #REQUIRED>

<!-- 
    Element:      title
    Description:  Provides a 4-5 word description about the advisory 
    Example:      <title>Buffer overflow vulnerability found in openssl-0.9.5</title> 
-->
<!ELEMENT title  (#PCDATA)>

<!-- 
    Element:      synopsis
    Description:  Small, to-the-point description about the GLSA

    Example:  <synopsis>
                  rsync has an exploitable buffer overflow that can lead to
                  remote compromise
              </synopsis>
-->
<!ELEMENT synopsis   (#PCDATA)>

<!-- 
    Element:      product
    Description:  Defines what type of security announcement this is.
    
                  Valid types are:
                  - ebuild         A Portage-provided ebuild has a security 
                                   issue
                  - informational  This GLSA is purely informational, no Gentoo
                                   system is affected
                  - infrastructure The security issue involves the Gentoo 
                                   infrastructure
    
                  The text contains one keyword that defines the issue.
                  Note: All type values but 'ebuild' are considered deprecated.
     
    Example: <product type="ebuild">openssl</product>
    Example: <product type="infrastructure">rsync mirror</product>
-->
<!ELEMENT product   (#PCDATA)>
<!ATTLIST product   type    (ebuild|infrastructure|informational) #REQUIRED>

<!--
    Element:      announced
    Description:  Date when the advisory is publicised
                  The format must be "YYYY-mm-dd"

    Example: <announced>2003-11-20</announced>
-->
<!ELEMENT announced (#PCDATA)>

<!--
    Element:      revised
    Description:  Last revision date of the GLSA
    Attribute:    @count: number of revisions
    
    Example: <revised count="02">2003-11-20</revised>
-->
<!ELEMENT revised (#PCDATA)>
<!ATTLIST revised count CDATA "01">

<!--
    Element:      bug
    Description:  Number of the bug on bugs.gentoo.org, if any
    Occurrence:    The bug element can occur 0, 1 or more times

    Example: <bug>34200</bug>
-->
<!ELEMENT bug       (#PCDATA)>

<!--
    Element:      access
    Description:  Type of access necessary to exploit the security issue
                  This element should only be used when product@type = 'ebuild'
    Occurrence:    The access element can occur 0 or 1 time
    
    Example: <access>Remote</access>
-->
<!ELEMENT access    (#PCDATA)>

<!--
    Element:      affected
    Description:  Describe what the affected subjects are.
    
                  If product@type = 'ebuild', the child elements are 'package'
                  If product@type = 'portage', the child elements are 'package'
                  If product@type = 'infrastructure', the child elements are 
                  'service'

-->
<!ELEMENT affected  (package*|service*)>

<!--
    Element:      package
    Description:  Provide all necessary information regarded the affected 
                  packages. It also contains information about the affected 
                  architectures, if automatic updates can be done and the update

                  The "update" attribute contains the path to the non-vulnerable
                  version of the package

                  The "auto" attribute contains either "yes" or "no" and tells 
                  Portage that the package can be updated automatically (to be 
                  implemented) without further user interaction

                  The "arch" attribute contains either the architecture (as used
                  by ACCEPT_KEYWORDS) or the "*" value (in case all 
                  architectures are affected)

    Occurrence:   The package element can occur 0, 1 or more times
    Example:      <package name="dev-libs/openssl" auto="yes" arch="*">
                    <vulnerable range="lt">0.9.6k</vulnerable>
                    <unaffected range="gt">0.9.6k</unaffected>
                  </package>
-->
<!ELEMENT package (vulnerable|unaffected)*>
<!ATTLIST package name      CDATA           #REQUIRED
                  auto      (yes|no)    #REQUIRED
                  arch      CDATA           #REQUIRED>

<!--
    Element:      vulnerable
    Description:  Version of the vulnerable package. Can be a range too
-->
<!ELEMENT vulnerable (#PCDATA)>
<!ATTLIST vulnerable range      (le|lt|eq|gt|ge|rlt|rle|rgt|rge)      #REQUIRED
                     slot       CDATA                 "*">

<!--
    Element:      unaffected
    Description:  Version of the fixed (or unaffected) package. In case the 
                  package is superseded by another package, you need to
                  define that package using the "name" attribute.

                  The r* range information is revision-specific. For instance, 
                  rge foo-1.2.3-r4  ==  >=foo-1.2.3-r4 && <foo-1.2.4

    Example:
                  <unaffected range="gt" name="foobar">2.0.0</unaffected>
-->
<!ELEMENT unaffected (#PCDATA)>
<!ATTLIST unaffected range      (le|lt|eq|gt|ge|rlt|rle|rgt|rge)      #REQUIRED
                     slot       CDATA                 "*"
                     name       CDATA                 #IMPLIED>

<!--
    Element:      service
    Description:  Provide information about the Gentoo services that are
                  affected by the security advisory. Portage must be able
                  to parse this information to make decisions (for instance, 
                  ignore an rsync server or a certain distfiles mirror).

                  The type attribute can be one of "rsync", "web", "mirror".

                  The fixed attribute (denoting if the problem has been solved)
                  can be one of "yes" or "no". If not used, the default value is
                  "no".
                  
    Occurrence:   The service element can occur 0, 1 or more times
    Example: <service type="rsync">rsync://rsync.someserver.tld/gentoo-portage</service>
-->
<!ELEMENT service (#PCDATA)>
<!ATTLIST service type (rsync|web|mirror) #REQUIRED
                  fixed (yes|no)          #IMPLIED>

<!--
    Element:      uri
    Description:  Link to the organisation involved in releasing the advisory
    Occurrence:   The uri element can occur 0, 1 or more times

    Example:      <uri link="http://www.cert.org">CERT</uri>
-->
<!ELEMENT uri       (#PCDATA)>
<!ATTLIST uri     link  CDATA   #IMPLIED>

<!--
    Element:      mail
    Description:  Mail address of the people involved in releasing the advisory
    Occurrence:   The mail element can occur 0, 1 or more times

    Example:      <mail link="some@person.com">Some Person</mail>
-->
<!ELEMENT mail      (#PCDATA)>
<!ATTLIST mail    link  CDATA   #REQUIRED>

<!--
    Element:      p
    Description:  Plain text
    Occurrence:   The "p" element can occur 0, 1 or more times and can contain
                  links or addresses

    Example:      <p>Please update your system</p>
-->
<!ELEMENT p (#PCDATA|mail|uri|b|i|br)*>

<!--
    Element:      code
    Description:  The code element contains text that should preserve whitespace
                  and is therefore useful for code listings or commands

    Example:      <code>emerge sync</code>
-->
<!ELEMENT code (#PCDATA)>

<!--
    Element:      background
    Description:  Provides a background of the affected package(s)/service(s)
                  The background element contains only "<p>"s in which the text 
                  is placed

-->
<!ELEMENT background  (p|ul|ol)*>

<!--
    Element:      description
    Description:  Provides a description about the security issue
                  The description element contains only "<p>"s.
-->
<!ELEMENT description (p|ul|ol|code)*>

<!--
    Element:      impact
    Description:  Provides information about the impact that the security issue 
                  can have

                  The "impact" element contains only "<p>"s.

                  The type element gives a short term, such as 
                  "Denial of Service", "Buffer Overflow", ...

-->
<!ELEMENT impact    (p|ul|ol)*>
<!ATTLIST impact    type    CDATA   #REQUIRED>

<!--
    Element:      workaround
    Description:  Provides information about how the security issue can be 
                  (temporarily) resolved through a work-around

                  The "workaround" element contains only "<p>"s and "<code>"s.
-->
<!ELEMENT workaround    (p|code|ul|ol)*>

<!--
    Element:      resolution
    Description:  Provides information about how the security issue can be 
                  resolved.

                  The "resolution" element contains only "<p>"s and "<code>"s.
-->
<!ELEMENT resolution  (p|code|ul|ol)*>

<!--
    Element:      references
    Description:  Provides links to resources / references available online.
                  
                  The "reference" element contains only "<uri>"s.
-->
<!ELEMENT references    (uri*)>

<!--
    Element:      ul
    Description:  Add an unnumbered listing; can only contain <li>'s
-->
<!ELEMENT ul            (li*)>

<!--
    Element:      ol
    Description:  Add a numbered listing; can only contain <li>'s
-->
<!ELEMENT ol            (li*)>

<!--
    Element:      li
    Description:  Element of a listing 
 
    Example:    <ul>
                  <li>This is element one</li>
                  <li>This is a second element</li>
                </ul>
-->
<!ELEMENT li            (#PCDATA)>

<!--
    Element:      b
    Description:  Bold text

    Example:    <b>this is bold</b>
-->
<!ELEMENT b             (#PCDATA)>

<!--
    Element:      i
    Description:  Input text (blue)

    Example:      The user has to type in <i>ls</i> to see.
-->
<!ELEMENT i             (#PCDATA)>

<!-- 
    Element:      br
    Description:  hard line break

    Example:      And then: <br/> 
                  KABLAM!
-->
<!ELEMENT br            (#PCDATA)>

<!-- 
    Element:      license
    Description:  Add license information

    Example:      <license/>
-->
<!ELEMENT license       (EMPTY)>

<!--
    Element:      metadata
    Description:  Metadata information for GLSAMaker

    Example:      <metadata tag="approved">Level 1</metadata>

    On request of plasmaroo, metadata can contain all elements again. 
-->
<!ELEMENT metadata  (#PCDATA|metadata)*>
<!ATTLIST metadata tag      CDATA #REQUIRED
                   revision CDATA #IMPLIED
                   author   CDATA #IMPLIED
                   timestamp CDATA #IMPLIED>

=== gentoo/gentoo/metadata/glsa/glsa-200405-06.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE glsa SYSTEM "http://www.gentoo.org/dtd/glsa.dtd">

<glsa id="200405-06">
  <title>libpng denial of service vulnerability</title>
  <synopsis>
    A bug in the libpng library can be abused to crash programs making use of
    that library to decode PNG images.
  </synopsis>
  <product type="ebuild">libpng</product>
  <announced>May 14, 2004</announced>
  <revised>May 14, 2004: 01</revised>
  <bug>49887</bug>
  <access>remote </access>
  <affected>
    <package name="media-libs/libpng" auto="yes" arch="*">
      <unaffected range="ge">1.2.5-r5</unaffected>
      <vulnerable range="le">1.2.5-r4</vulnerable>
    </package>
  </affected>
  <background>
    <p>
    libpng is a standard library used to process PNG (Portable Network
    Graphics) images.
    </p>
  </background>
  <description>
    <p>
    libpng provides two functions (png_chunk_error and png_chunk_warning) for
    default error and warning messages handling. These functions do not perform
    proper bounds checking on the provided message, which is limited to 64
    bytes. Programs linked against this library may crash when handling a
    malicious PNG image.
    </p>
  </description>
  <impact type="normal">
    <p>
    This vulnerability could be used to crash various programs using the libpng
    library, potentially resulting in a denial of service attack on vulnerable
    daemon processes.
    </p>
  </impact>
  <workaround>
    <p>
    There is no known workaround at this time. All users are advised to upgrade
    to the latest available version of libpng.
    </p>
  </workaround>
  <resolution>
    <p>
    All users of libpng should upgrade to the latest stable version:
    </p>
    <code>
    # emerge sync

    # emerge -pv ">=media-libs/libpng-1.2.5-r5"
    # emerge ">=media-libs/libpng-1.2.5-r5"</code>
    <p>
    You should also run revdep-rebuild to rebuild any packages that depend on
    older versions of libpng :
    </p>
    <code>
    # revdep-rebuild</code>
  </resolution>
  <references>
    <uri link="http://cve.mitre.org/cgi-bin/cvename.cgi?name=CAN-2004-0421">CAN-2004-0421</uri>
  </references>
  <metadata tag="submitter">
    koon
  </metadata>
</glsa>

=== gentoo/gentoo/metadata/glsa/glsa-200407-14.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE glsa SYSTEM "http://www.gentoo.org/dtd/glsa.dtd">

<glsa id="200407-14">
  <title>Unreal Tournament 2003/2004: Buffer overflow in 'secure' queries</title>
  <synopsis>
    Game servers based on the Unreal engine are vulnerable to remote code
    execution through malformed 'secure' queries.
  </synopsis>
  <product type="ebuild">Unreal Tournament</product>
  <announced>July 19, 2004</announced>
  <revised>July 19, 2004: 01</revised>
  <bug>54726</bug>
  <access>remote</access>
  <affected>
    <package name="games-fps/ut2003" auto="yes" arch="*">
      <unaffected range="ge">2225-r3</unaffected>
      <vulnerable range="le">2225-r2</vulnerable>
    </package>
    <package name="games-server/ut2003-ded" auto="yes" arch="*">
      <unaffected range="ge">2225-r2</unaffected>
      <vulnerable range="le">2225-r1</vulnerable>
    </package>
    <package name="games-fps/ut2004" auto="yes" arch="*">
      <unaffected range="ge">3236</unaffected>
      <vulnerable range="lt">3236</vulnerable>
    </package>
    <package name="games-fps/ut2004-demo" auto="yes" arch="*">
      <unaffected range="ge">3120-r4</unaffected>
      <vulnerable range="le">3120-r3</vulnerable>
    </package>
  </affected>
  <background>
    <p>
    Unreal Tournament 2003 and 2004 are popular first-person-shooter games.
    They are both based on the Unreal engine, and can be used in a game server
    / client setup.
    </p>
  </background>
  <description>
    <p>
    The Unreal-based game servers support a specific type of query called
    'secure'. Part of the Gamespy protocol, this query is used to ask if the
    game server is able to calculate an exact response using a provided string.
    Luigi Auriemma found that sending a long 'secure' query triggers a buffer
    overflow in the game server.
    </p>
  </description>
  <impact type="high">
    <p>
    By sending a malicious UDP-based 'secure' query, an attacker could execute
    arbitrary code on the game server.
    </p>
  </impact>
  <workaround>
    <p>
    Users can avoid this vulnerability by not using Unreal Tournament to host
    games as a server. All users running a server should upgrade to the latest
    versions.
    </p>
  </workaround>
  <resolution>
    <p>
    All Unreal Tournament users should upgrade to the latest available
    versions:
    </p>
    <code>
    # emerge sync

    # emerge -pv ">=games-fps/ut2003-2225-r3"
    # emerge ">=games-fps/ut2003-2225-r3"

    # emerge -pv ">=games-server/ut2003-ded-2225-r2"
    # emerge ">=games-server/ut2003-ded-2225-r2"

    # emerge -pv ">=games-fps/ut2004-3236"
    # emerge ">=games-fps/ut2004-3236"

    # emerge -pv ">=games-fps/ut2004-demo-3120-r4"
    # emerge ">=games-fps/ut2004-demo-3120-r4"</code>
  </resolution>
  <references>
    <uri link="http://aluigi.altervista.org/adv/unsecure-adv.txt">Luigi Auriemma advisory</uri>
    <uri link="http://cve.mitre.org/cgi-bin/cvename.cgi?name=CAN-2004-0608">CAN-2004-0608</uri>
  </references>
  <metadata tag="submitter">
    koon
  </metadata>
</glsa>

=== gentoo/gentoo/metadata/glsa/glsa-200506-22.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE glsa SYSTEM "http://www.gentoo.org/dtd/glsa.dtd">

<glsa id="200506-22">
  <title>sudo: Arbitrary command execution</title>
  <synopsis>
    A vulnerability in sudo may allow local users to elevate privileges.
  </synopsis>
  <product type="ebuild">sudo</product>
  <announced>June 23, 2005</announced>
  <revised>June 23, 2005: 01</revised>
  <bug>96618</bug>
  <access>local</access>
  <affected>
    <package name="app-admin/sudo" auto="yes" arch="*">
      <unaffected range="ge">1.6.8_p9</unaffected>
      <vulnerable range="lt">1.6.8_p9</vulnerable>
    </package>
  </affected>
  <background>
    <p>
    sudo allows a system administrator to give users the ability to
    run commands as other users.
    </p>
  </background>
  <description>
    <p>
    The sudoers file is used to define the actions sudo users are
    permitted to perform. Charles Morris discovered that a specific layout
    of the sudoers file could cause the results of an internal check to be
    clobbered, leaving sudo vulnerable to a race condition.
    </p>
  </description>
  <impact type="normal">
    <p>
    Successful exploitation would permit a local sudo user to execute
    arbitrary commands as another user.
    </p>
  </impact>
  <workaround>
    <p>
    Reorder the sudoers file using the visudo utility to ensure the
    'ALL' pseudo-command precedes other command definitions.
    </p>
  </workaround>
  <resolution>
    <p>
    All sudo users should upgrade to the latest version:
    </p>
    <code>
    # emerge --sync
    # emerge --ask --oneshot --verbose &quot;&gt;=app-admin/sudo-1.6.8_p9&quot;</code>
  </resolution>
  <references>
    <uri link="http://www.sudo.ws/sudo/alerts/path_race.html">Sudo Announcement</uri>
  </references>
  <metadata tag="requester" timestamp="Tue, 21 Jun 2005 20:05:11 +0000">
    koon
  </metadata>
  <metadata tag="submitter" timestamp="Wed, 22 Jun 2005 15:18:20 +0000">
    taviso
  </metadata>
  <metadata tag="bugReady" timestamp="Thu, 23 Jun 2005 06:48:01 +0000">
    jaervosz
  </metadata>
</glsa>

=== gentoo/gentoo/glsa-200611-12.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE glsa SYSTEM "http://www.gentoo.org/dtd/glsa.dtd">
<glsa id="200611-12">
  <title>Ruby: Denial of Service vulnerability</title>
  <synopsis>
    The Ruby cgi.rb CGI library is vulnerable to a Denial of Service attack.
  </synopsis>
  <product type="ebuild">ruby</product>
  <announced>2006-11-20</announced>
  <revised>2009-06-11: 02</revised>
  <bug>153497</bug>
  <access>remote</access>
  <affected>
    <package name="dev-lang/ruby" auto="yes" arch="*">
      <unaffected range="ge">1.8.5-r3</unaffected>
      <vulnerable range="lt">1.8.5-r3</vulnerable>
    </package>
  </affected>
  <background>
    <p>
    Ruby is a dynamic, open source programming language with a focus on
    simplicity and productivity.
    </p>
  </background>
  <description>
    <p>
    Zed Shaw, Jeremy Kemper, and Jamis Buck of the Mongrel project reported
    that the CGI library shipped with Ruby is vulnerable to a remote Denial
    of Service by an unauthenticated user.
    </p>
  </description>
  <impact type="normal">
    <p>
    The vulnerability can be exploited by sending the cgi.rb library an
    HTTP request with multipart MIME encoding that contains a malformed
    MIME boundary specifier beginning with "-" instead of "--". Successful
    exploitation of the vulnerability causes the library to go into an
    infinite loop waiting for additional nonexistent input.
    </p>
  </impact>
  <workaround>
    <p>
    There is no known workaround at this time.
    </p>
  </workaround>
  <resolution>
    <p>
    All Ruby users should upgrade to the latest version:
    </p>
    <code>
    # emerge --sync
    # emerge --ask --oneshot --verbose "&gt;=dev-lang/ruby-1.8.5-r3"</code>
  </resolution>
  <references>
    <uri link="https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2006-5467">CVE-2006-5467</uri>
  </references>
  <metadata tag="submitter" timestamp="2006-11-10T13:03:41Z">
    aetius
  </metadata>
  <metadata tag="bugReady" timestamp="2006-11-15T21:17:28Z">
    vorlon
  </metadata>
</glsa>

=== gentoo/gentoo/metadata/glsa/glsa-200705-17.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE glsa SYSTEM "http://www.gentoo.org/dtd/glsa.dtd">

<glsa id="200705-17">
  <title>Apache mod_security: Rule bypass</title>
  <synopsis>
    A vulnerability has been discovered in mod_security, allowing a remote
    attacker to bypass rules.
  </synopsis>
  <product type="ebuild">mod_security</product>
  <announced>May 17, 2007</announced>
  <revised>December 30, 2007: 02</revised>
  <bug>169778</bug>
  <access>remote</access>
  <affected>
    <package name="www-apache/mod_security" auto="yes" arch="*">
      <unaffected range="ge">2.1.1</unaffected>
      <vulnerable range="lt">2.1.1</vulnerable>
    </package>
  </affected>
  <background>
    <p>
    mod_security is an Apache module designed for enhancing the security of
    the Apache web server.
    </p>
  </background>
  <description>
    <p>
    Stefan Esser discovered that mod_security processes NULL characters as
    terminators in POST requests using the
    application/x-www-form-urlencoded encoding type, while other parsers
    used in web applications do not.
    </p>
  </description>
  <impact type="low">
    <p>
    A remote attacker could send a specially crafted POST request, possibly
    bypassing the module ruleset and leading to the execution of arbitrary
    code in the scope of the web server with the rights of the user running
    the web server.
    </p>
  </impact>
  <workaround>
    <p>
    There is no known workaround at this time.
    </p>
  </workaround>
  <resolution>
    <p>
    All mod_security users should upgrade to the latest version:
    </p>
    <code>
    # emerge --sync
    # emerge --ask --oneshot --verbose &quot;&gt;=www-apache/mod_security-2.1.1&quot;</code>
  </resolution>
  <references>
    <uri link="http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2007-1359">CVE-2007-1359</uri>
  </references>
  <metadata tag="requester" timestamp="Fri, 11 May 2007 23:14:33 +0000">
    shellsage
  </metadata>
  <metadata tag="bugReady" timestamp="Sun, 13 May 2007 04:49:45 +0000">
    shellsage
  </metadata>
  <metadata tag="submitter" timestamp="Sun, 13 May 2007 13:46:57 +0000">
    p-y
  </metadata>
</glsa>

=== gentoo/gentoo/glsa-200903-40.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE glsa SYSTEM "http://www.gentoo.org/dtd/glsa.dtd">
<glsa id="200903-40">
  <title>Analog: Denial of Service</title>
  <synopsis>
    A Denial of Service vulnerability was discovered in Analog.
  </synopsis>
  <product type="ebuild">analog</product>
  <announced>2009-03-29</announced>
  <revised count="01">2009-03-29</revised>
  <bug>249140</bug>
  <access>local</access>
  <affected>
    <package name="app-admin/analog" auto="yes" arch="*">
      <unaffected range="ge">6.0-r2</unaffected>
      <vulnerable range="lt">6.0-r2</vulnerable>
    </package>
  </affected>
  <background>
    <p>
    Analog is a a webserver log analyzer.
    </p>
  </background>
  <description>
    <p>
    Diego E. Petteno reported that the Analog package in Gentoo is built
    with its own copy of bzip2, making it vulnerable to CVE-2008-1372 (GLSA
    200804-02).
    </p>
  </description>
  <impact type="normal">
    <p>
    A local attacker could place specially crafted log files into a log
    directory being analyzed by analog, e.g. /var/log/apache, resulting in
    a crash when being processed by the application.
    </p>
  </impact>
  <workaround>
    <p>
    There is no known workaround at this time.
    </p>
  </workaround>
  <resolution>
    <p>
    All Analog users should upgrade to the latest version:
    </p>
    <code>
    # emerge --sync
    # emerge --ask --oneshot --verbose "&gt;=app-admin/analog-6.0-r2"</code>
    <p>
    NOTE: Analog is now linked against the system bzip2 library.
    </p>
  </resolution>
  <references>
    <uri link="https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2008-1372">CVE-2008-1372</uri>
    <uri link="https://www.gentoo.org/security/en/glsa/glsa-200804-02.xml">GLSA 200804-02</uri>
  </references>
  <metadata tag="requester" timestamp="2008-12-21T20:13:59Z">
    keytoaster
  </metadata>
  <metadata tag="submitter" timestamp="2009-03-26T12:22:59Z">
    p-y
  </metadata>
  <metadata tag="bugReady" timestamp="2009-03-26T12:23:07Z">
    p-y
  </metadata>
</glsa>
