=== gentoo/gentoo/metadata/dtd/glsa.dtd
<!-- $Header: /var/cvsroot/gentoo/xml/htdocs/dtd/glsa.dtd,v 1.17 2008/04/04 17:04:39 neysx Exp $ -->
<!ELEMENT glsa  (title,synopsis,product,announced,revised,bug*,access?,affected,background?,description,impact,workaround,resolution,references,license?,metadata*)>
<!ATTLIST glsa  id  CDATA   #REQUIRED>

<!-- 
    Element:      title
    Description:  Provides a 4-5 word description about the advisory 
    Example:      <title>Buffer overflow vulnerability found in openssl-0.9.5</title> 
-->
<!ELEMENT title  (#PCDATA)>

<!-- 
    Element:      synopsis
    Description:  Small, to-the-point description about the GLSA

    Example:  <synopsis>
                  rsync has an exploitable buffer overflow that can lead to
                  remote compromise
              </synopsis>
-->
<!ELEMENT synopsis   (#PCDATA)>

<!-- 
    Element:      product
    Description:  Defines what type of security announcement this is.
    
                  Valid types are:
                  - ebuild         A Portage-provided ebuild has a security 
                                   issue
                  - informational  This GLSA is purely informational, no Gentoo
                                   system is affected
                  - infrastructure The security issue involves the Gentoo 
                                   infrastructure
    
                  The text contains one keyword that defines the issue.
                  Note: All type values but 'ebuild' are considered deprecated.
     
    Example: <product type="ebuild">openssl</product>
    Example: <product type="infrastructure">rsync mirror</product>
-->
<!ELEMENT product   (#PCDATA)>
<!ATTLIST product   type    (ebuild|infrastructure|informational) #REQUIRED>

<!--
    Element:      announced
    Description:  Date when the advisory is publicised
                  The format must be "YYYY-mm-dd"

    Example: <announced>2003-11-20</announced>
-->
<!ELEMENT announced (#PCDATA)>

<!--
    Element:      revised
    Description:  Last revision date of the GLSA
    Attribute:    @count: number of revisions
    
    Example: <revised count="02">2003-11-20</revised>
-->
<!ELEMENT revised (#PCDATA)>
<!ATTLIST revised count CDATA "01">

<!--
    Element:      bug
    Description:  Number of the bug on bugs.gentoo.org, if any
    Occurrence:    The bug element can occur 0, 1 or more times

    Example: <bug>34200</bug>
-->
<!ELEMENT bug       (#PCDATA)>

<!--
    Element:      access
    Description:  Type of access necessary to exploit the security issue
                  This element should only be used when product@type = 'ebuild'
    Occurrence:    The access element can occur 0 or 1 time
    
    Example: <access>Remote</access>
-->
<!ELEMENT access    (#PCDATA)>

<!--
    Element:      affected
    Description:  Describe what the affected subjects are.
    
                  If product@type = 'ebuild', the child elements are 'package'
                  If product@type = 'portage', the child elements are 'package'
                  If product@type = 'infrastructure', the child elements are 
                  'service'

-->
<!ELEMENT affected  (package*|service*)>

<!--
    Element:      package
    Description:  Provide all necessary information regarded the affected 
                  packages. It also contains information about the affected 
                  architectures, if automatic updates can be done and the update

                  The "update" attribute contains the path to the non-vulnerable
                  version of the package

                  The "auto" attribute contains either "yes" or "no" and tells 
                  Portage that the package can be updated automatically (to be 
                  implemented) without further user interaction

                  The "arch" attribute contains either the architecture (as used
                  by ACCEPT_KEYWORDS) or the "*" value (in case all 
                  architectures are affected)

    Occurrence:   The package element can occur 0, 1 or more times
    Example:      <package name="dev-libs/openssl" auto="yes" arch="*">
                    <vulnerable range="lt">0.9.6k</vulnerable>
                    <unaffected range="gt">0.9.6k</unaffected>
                  </package>
-->
<!ELEMENT package (vulnerable|unaffected)*>
<!ATTLIST package name      CDATA           #REQUIRED
                  auto      (yes|no)    #REQUIRED
                  arch      CDATA           #REQUIRED>

<!--
    Element:      vulnerable
    Description:  Version of the vulnerable package. Can be a range too
-->
<!ELEMENT vulnerable (#PCDATA)>
<!ATTLIST vulnerable range      (le|lt|eq|gt|ge|rlt|rle|rgt|rge)      #REQUIRED
                     slot       CDATA                 "*">

<!--
    Element:      unaffected
    Description:  Version of the fixed (or unaffected) package. In case the 
                  package is superseded by another package, you need to
                  define that package using the "name" attribute.

                  The r* range information is revision-specific. For instance, 
                  rge foo-1.2.3-r4  ==  >=foo-1.2.3-r4 && <foo-1.2.4

    Example:
                  <unaffected range="gt" name="foobar">2.0.0</unaffected>
-->
<!ELEMENT unaffected (#PCDATA)>
<!ATTLIST unaffected range      (le|lt|eq|gt|ge|rlt|rle|rgt|rge)      #REQUIRED
                     slot       CDATA                 "*"
                     name       CDATA                 #IMPLIED>

<!--
    Element:      service
    Description:  Provide information about the Gentoo services that are
                  affected by the security advisory. Portage must be able
                  to parse this information to make decisions (for instance, 
                  ignore an rsync server or a certain distfiles mirror).

                  The type attribute can be one of "rsync", "web", "mirror".

                  The fixed attribute (denoting if the problem has been solved)
                  can be one of "yes" or "no". If not used, the default value is
                  "no".
                  
    Occurrence:   The service element can occur 0, 1 or more times
    Example: <service type="rsync">rsync://rsync.someserver.tld/gentoo-portage</service>
-->
<!ELEMENT service (#PCDATA)>
<!ATTLIST service type (rsync|web|mirror) #REQUIRED
                  fixed (yes|no)          #IMPLIED>

<!--
    Element:      uri
    Description:  Link to the organisation involved in releasing the advisory
    Occurrence:   The uri element can occur 0, 1 or more times

    Example:      <uri link="http://www.cert.org">CERT</uri>
-->
<!ELEMENT uri       (#PCDATA)>
<!ATTLIST uri     link  CDATA   #IMPLIED>

<!--
    Element:      mail
    Description:  Mail address of the people involved in releasing the advisory
    Occurrence:   The mail element can occur 0, 1 or more times

    Example:      <mail link="some@person.com">Some Person</mail>
-->
<!ELEMENT mail      (#PCDATA)>
<!ATTLIST mail    link  CDATA   #REQUIRED>

<!--
    Element:      p
    Description:  Plain text
    Occurrence:   The "p" element can occur 0, 1 or more times and can contain
                  links or addresses

    Example:      <p>Please update your system</p>
-->
<!ELEMENT p (#PCDATA|mail|uri|b|i|br)*>

<!--
    Element:      code
    Description:  The code element contains text that should preserve whitespace
                  and is therefore useful for code listings or commands

    Example:      <code>emerge sync</code>
-->
<!ELEMENT code (#PCDATA)>

<!--
    Element:      background
    Description:  Provides a background of the affected package(s)/service(s)
                  The background element contains only "<p>"s in which the text 
                  is placed

-->
<!ELEMENT background  (p|ul|ol)*>

<!--
    Element:      description
    Description:  Provides a description about the security issue
                  The description element contains only "<p>"s.
-->
<!ELEMENT description (p|ul|ol|code)*>

<!--
    Element:      impact
    Description:  Provides information about the impact that the security issue 
                  can have

                  The "impact" element contains only "<p>"s.

                  The type element gives a short term, such as 
                  "Denial of Service", "Buffer Overflow", ...

-->
<!ELEMENT impact    (p|ul|ol)*>
<!ATTLIST impact    type    CDATA   #REQUIRED>

<!--
    Element:      workaround
    Description:  Provides information about how the security issue can be 
                  (temporarily) resolved through a work-around

                  The "workaround" element contains only "<p>"s and "<code>"s.
-->
<!ELEMENT workaround    (p|code|ul|ol)*>

<!--
    Element:      resolution
    Description:  Provides information about how the security issue can be 
                  resolved.

                  The "resolution" element contains only "<p>"s and "<code>"s.
-->
<!ELEMENT resolution  (p|code|ul|ol)*>

<!--
    Element:      references
    Description:  Provides links to resources / references available online.
                  
                  The "reference" element contains only "<uri>"s.
-->
<!ELEMENT references    (uri*)>

<!--
    Element:      ul
    Description:  Add an unnumbered listing; can only contain <li>'s
-->
<!ELEMENT ul            (li*)>

<!--
    Element:      ol
    Description:  Add a numbered listing; can only contain <li>'s
-->
<!ELEMENT ol            (li*)>

<!--
    Element:      li
    Description:  Element of a listing 
 
    Example:    <ul>
                  <li>This is element one</li>
                  <li>This is a second element</li>
                </ul>
-->
<!ELEMENT li            (#PCDATA)>

<!--
    Element:      b
    Description:  Bold text

    Example:    <b>this is bold</b>
-->
<!ELEMENT b             (#PCDATA)>

<!--
    Element:      i
    Description:  Input text (blue)

    Example:      The user has to type in <i>ls</i> to see.
-->
<!ELEMENT i             (#PCDATA)>

<!-- 
    Element:      br
    Description:  hard line break

    Example:      And then: <br/> 
                  KABLAM!
-->
<!ELEMENT br            (#PCDATA)>

<!-- 
    Element:      license
    Description:  Add license information

    Example:      <license/>
-->
<!ELEMENT license       (EMPTY)>

<!--
    Element:      metadata
    Description:  Metadata information for GLSAMaker

    Example:      <metadata tag="approved">Level 1</metadata>

    On request of plasmaroo, metadata can contain all elements again. 
-->
<!ELEMENT metadata  (#PCDATA|metadata)*>
<!ATTLIST metadata tag      CDATA #REQUIRED
                   revision CDATA #IMPLIED
                   author   CDATA #IMPLIED
                   timestamp CDATA #IMPLIED>

=== gentoo/gentoo/metadata/glsa/glsa-200501-22.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE glsa SYSTEM "http://www.gentoo.org/dtd/glsa.dtd">

<glsa id="200501-22">
  <title>poppassd_pam: Unauthorized password changing</title>
  <synopsis>
    poppassd_pam allows anyone to change any user's password without
    authenticating the user first.
  </synopsis>
  <product type="ebuild">poppassd_pam</product>
  <announced>January 11, 2005</announced>
  <revised>January 11, 2005: 01</revised>
  <bug>75820</bug>
  <access>remote</access>
  <affected>
    <package name="net-mail/poppassd_ceti" auto="yes" arch="*">
      <unaffected range="ge">1.8.4</unaffected>
      <vulnerable range="le">1.0</vulnerable>
    </package>
    <package name="net-mail/poppassd_pam" auto="yes" arch="*">
      <vulnerable range="le">1.0</vulnerable>
    </package>
  </affected>
  <background>
    <p>
    poppassd_pam is a PAM-enabled server for changing system passwords
    that can be used to change POP server passwords.
    </p>
  </background>
  <description>
    <p>
    Gentoo Linux developer Marcus Hanwell discovered that poppassd_pam
    did not check that the old password was valid before changing
    passwords. Our investigation revealed that poppassd_pam did not call
    pam_authenticate before calling pam_chauthtok.
    </p>
  </description>
  <impact type="high">
    <p>
    A remote attacker could change the system password of any user,
    including root. This leads to a complete compromise of the POP
    accounts, and may also lead to a complete root compromise of the
    affected server, if it also provides shell access authenticated using
    system passwords.
    </p>
  </impact>
  <workaround>
    <p>
    There is no known workaround at this time.
    </p>
  </workaround>
  <resolution>
    <p>
    All poppassd_pam users should migrate to the new package called
    poppassd_ceti:
    </p>
    <code>
    # emerge --sync
    # emerge --ask --oneshot --verbose &quot;&gt;=net-mail/poppassd_ceti-1.8.4&quot;</code>
    <p>
    Note: Portage will automatically replace the poppassd_pam
    package by the poppassd_ceti package.
    </p>
  </resolution>
  <references>
    <uri link="http://cve.mitre.org/cgi-bin/cvename.cgi?name=CAN-2005-0002">CAN-2005-0002</uri>
  </references>
  <metadata tag="requester" timestamp="Tue, 11 Jan 2005 08:56:45 +0000">
    koon
  </metadata>
  <metadata tag="submitter" timestamp="Tue, 11 Jan 2005 12:12:22 +0000">
    koon
  </metadata>
  <metadata tag="bugReady" timestamp="Tue, 11 Jan 2005 19:52:14 +0000">
    koon
  </metadata>
</glsa>

=== gentoo/gentoo/metadata/glsa/glsa-200510-16.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE glsa SYSTEM "http://www.gentoo.org/dtd/glsa.dtd">

<glsa id="200510-16">
  <title>phpMyAdmin: Local file inclusion vulnerability</title>
  <synopsis>
    phpMyAdmin contains a local file inclusion vulnerability that may lead to
    the execution of arbitrary code.
  </synopsis>
  <product type="ebuild">phpmyadmin</product>
  <announced>October 17, 2005</announced>
  <revised>May 22, 2006: 02</revised>
  <bug>108939</bug>
  <access>local</access>
  <affected>
    <package name="dev-db/phpmyadmin" auto="yes" arch="*">
      <unaffected range="ge">2.6.4_p2</unaffected>
      <vulnerable range="lt">2.6.4_p2</vulnerable>
    </package>
  </affected>
  <background>
    <p>
    phpMyAdmin is a tool written in PHP intended to handle the
    administration of MySQL over the web.
    </p>
  </background>
  <description>
    <p>
    Maksymilian Arciemowicz reported that in
    libraries/grab_globals.lib.php, the $__redirect parameter was not
    correctly validated. Systems running PHP in safe mode are not affected.
    </p>
  </description>
  <impact type="normal">
    <p>
    A local attacker may exploit this vulnerability by sending malicious
    requests, causing the execution of arbitrary code with the rights of
    the user running the web server.
    </p>
  </impact>
  <workaround>
    <p>
    Run PHP in safe mode.
    </p>
  </workaround>
  <resolution>
    <p>
    All phpMyAdmin users should upgrade to the latest version:
    </p>
    <code>
    # emerge --sync
    # emerge --ask --oneshot --verbose &quot;&gt;=dev-db/phpmyadmin-2.6.4_p2&quot;</code>
  </resolution>
  <references>
    <uri link="http://www.phpmyadmin.net/home_page/security.php?issue=PMASA-2005-4">PMASA-2005-4</uri>
    <uri link="http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2005-3299">CVE-2005-3299</uri>
  </references>
  <metadata tag="requester" timestamp="Sat, 15 Oct 2005 08:08:40 +0000">
    koon
  </metadata>
  <metadata tag="bugReady" timestamp="Sun, 16 Oct 2005 19:41:39 +0000">
    koon
  </metadata>
  <metadata tag="submitter" timestamp="Mon, 17 Oct 2005 03:54:58 +0000">
    adir
  </metadata>
</glsa>

=== gentoo/gentoo/metadata/glsa/glsa-200909-16.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE glsa SYSTEM "http://www.gentoo.org/dtd/glsa.dtd">

<glsa id="200909-16">
  <title>Wireshark: Denial of Service</title>
  <synopsis>
    Multiple vulnerabilities have been discovered in Wireshark which allow for
    Denial of Service.
  </synopsis>
  <product type="ebuild">wireshark</product>
  <announced>September 13, 2009</announced>
  <revised>September 13, 2009: 01</revised>
  <bug>278564</bug>
  <access>remote</access>
  <affected>
    <package name="net-analyzer/wireshark" auto="yes" arch="*">
      <unaffected range="ge">1.2.1</unaffected>
      <vulnerable range="lt">1.2.1</vulnerable>
    </package>
  </affected>
  <background>
    <p>
    Wireshark is a versatile network protocol analyzer.
    </p>
  </background>
  <description>
    <p>
    Multiple vulnerabilities were discovered in Wireshark:
    </p>
    <ul>
    <li>A
    buffer overflow in the IPMI dissector related to an array index error
    (CVE-2009-2559).</li>
    <li>Multiple unspecified vulnerabilities in the
    Bluetooth L2CAP, RADIUS, and MIOP dissectors (CVE-2009-2560).</li>
    <li>An unspecified vulnerability in the sFlow dissector
    (CVE-2009-2561).</li>
    <li>An unspecified vulnerability in the AFS
    dissector (CVE-2009-2562).</li>
    <li>An unspecified vulnerability in the
    Infiniband dissector when running on unspecified platforms
    (CVE-2009-2563).</li>
    </ul>
  </description>
  <impact type="normal">
    <p>
    A remote attacker could exploit these vulnerabilities by sending
    specially crafted packets on a network being monitored by Wireshark or
    by enticing a user to read a malformed packet trace file to cause a
    Denial of Service.
    </p>
  </impact>
  <workaround>
    <p>
    There is no known workaround at this time.
    </p>
  </workaround>
  <resolution>
    <p>
    All Wireshark users should upgrade to the latest version:
    </p>
    <code>
    # emerge --sync
    # emerge --ask --oneshot --verbose &quot;&gt;=net-analyzer/wireshark-1.2.1&quot;</code>
  </resolution>
  <references>
    <uri link="http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2009-2559">CVE-2009-2559</uri>
    <uri link="http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2009-2560">CVE-2009-2560</uri>
    <uri link="http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2009-2561">CVE-2009-2561</uri>
    <uri link="http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2009-2562">CVE-2009-2562</uri>
    <uri link="http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2009-2563">CVE-2009-2563</uri>
  </references>
  <metadata tag="requester" timestamp="Tue, 25 Aug 2009 10:03:54 +0000">
    keytoaster
  </metadata>
  <metadata tag="submitter" timestamp="Tue, 25 Aug 2009 13:10:41 +0000">
    keytoaster
  </metadata>
  <metadata tag="bugReady" timestamp="Tue, 25 Aug 2009 13:28:12 +0000">
    keytoaster
  </metadata>
</glsa>

=== gentoo/gentoo/metadata/glsa/glsa-200401-04.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE glsa SYSTEM "http://www.gentoo.org/dtd/glsa.dtd">

<glsa id="200401-04">
  <title>GAIM 0.75 Remote overflows</title>
  <synopsis>
    Various overflows in the handling of AIM DirectIM packets was revealed in
    GAIM that could lead to a remote compromise of the IM client.
  </synopsis>
  <product type="ebuild">GAIM</product>
  <announced>January 26, 2004</announced>
  <revised>January 26, 2004: 01</revised>
  <bug>39470</bug>
  <access>man-in-the-middle</access>
  <affected>
    <package name="net-im/gaim" auto="yes" arch="*">
      <unaffected range="ge">0.75-r7</unaffected>
      <vulnerable range="lt">0.75-r7</vulnerable>
    </package>
  </affected>
  <background>
    <p>
    Gaim is a multi-platform and multi-protocol instant messaging
    client.  It is compatible with AIM , ICQ, MSN Messenger, Yahoo,
    IRC, Jabber, Gadu-Gadu, and the Zephyr networks.
    </p>
  </background>
  <description>
    <p>
    Yahoo changed the authentication methods to their IM servers,
    rendering GAIM useless. The GAIM team released a rushed release
    solving this issue, however, at the same time a code audit
    revealed 12 new vulnerabilities.
    </p>
  </description>
  <impact type="normal">
    <p>
    Due to the nature of instant messaging many of these bugs require
    man-in-the-middle attacks between the client and the server. But
    the underlying protocols are easy to implement and attacking
    ordinary TCP sessions is a fairly simple task. As a result, all
    users are advised to upgrade their GAIM installation.
    </p>
    <ul>
      <li>
        Users of GAIM 0.74 or below are affected by 7 of the
        vulnerabilities and are encouraged to upgrade.
      </li>
      <li>
        Users of GAIM 0.75 are affected by 11 of the vulnerabilities
        and are encouraged to upgrade to the patched version of GAIM
        offered by Gentoo.
      </li>
      <li>
        Users of GAIM 0.75-r6 are only affected by
        4 of the vulnerabilities, but are still urged to upgrade to
        maintain security.
      </li>
    </ul>
  </impact>
  <workaround>
    <p>
    There is no immediate workaround; a software upgrade is required.
    </p>
  </workaround>
  <resolution>
    <p>
    All users are recommended to upgrade GAIM to 0.75-r7.
    </p>
    <code>
    $> emerge sync
    $> emerge -pv ">=net-im/gaim-0.75-r7"
    $> emerge ">=net-im/gaim-0.75-r7"</code>
  </resolution>
  <references>
    <uri link="http://www.securityfocus.com/archive/1/351235/2004-01-23/2004-01-29/0">Security advisory from Stefan Esser</uri>
  </references>
</glsa>

=== gentoo/gentoo/metadata/glsa/glsa-201702-05.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE glsa SYSTEM "http://www.gentoo.org/dtd/glsa.dtd">
<glsa id="201702-05">
  <title>Lsyncd: Remote execution of arbitrary code</title>
  <synopsis>A vulnerability in Lsyncd allows execution of arbitrary code.</synopsis>
  <product type="ebuild">lsyncd</product>
  <announced>2017-02-10</announced>
  <revised>2017-02-10: 1</revised>
  <bug>529678</bug>
  <access>local, remote</access>
  <affected>
    <package name="app-admin/lsyncd" auto="yes" arch="*">
      <unaffected range="ge">2.1.6</unaffected>
      <vulnerable range="lt">2.1.6</vulnerable>
    </package>
  </affected>
  <background>
    <p>A daemon to synchronize local directories using rsync.</p>
  </background>
  <description>
    <p>default-rsyncssh.lua in Lsyncd performed insufficient sanitising of
      filenames.
    </p>
  </description>
  <impact type="normal">
    <p>An attacker, able to control files processed by Lsyncd, could possibly
      execute arbitrary code with the privileges of the process or cause a
      Denial of Service condition.
    </p>
  </impact>
  <workaround>
    <p>There is no known workaround at this time.</p>
  </workaround>
  <resolution>
    <p>All Lsyncd users should upgrade to the latest version:</p>
    
    <code>
      # emerge --sync
      # emerge --ask --oneshot --verbose "&gt;=app-admin/lsyncd-2.1.6"
    </code>
  </resolution>
  <references>
    <uri link="http://nvd.nist.gov/nvd.cfm?cvename=CVE-2014-8990">CVE-2014-8990</uri>
  </references>
  <metadata tag="requester" timestamp="2017-02-01T09:30:15Z">b-man</metadata>
  <metadata tag="submitter" timestamp="2017-02-10T23:08:07Z">whissi</metadata>
</glsa>

=== gentoo/gentoo/metadata/glsa/glsa-200509-13.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE glsa SYSTEM "http://www.gentoo.org/dtd/glsa.dtd">

<glsa id="200509-13">
  <title>Clam AntiVirus: Multiple vulnerabilities</title>
  <synopsis>
    Clam AntiVirus is subject to vulnerabilities ranging from Denial of Service
    to execution of arbitrary code when handling compressed executables.
  </synopsis>
  <product type="ebuild">clamav</product>
  <announced>September 19, 2005</announced>
  <revised>September 19, 2005: 01</revised>
  <bug>106279</bug>
  <access>remote</access>
  <affected>
    <package name="app-antivirus/clamav" auto="yes" arch="*">
      <unaffected range="ge">0.87</unaffected>
      <vulnerable range="lt">0.87</vulnerable>
    </package>
  </affected>
  <background>
    <p>
    Clam AntiVirus is a GPL anti-virus toolkit, designed for
    integration with mail servers to perform attachment scanning. Clam
    AntiVirus also provides a command line scanner and a tool for fetching
    updates of the virus database.
    </p>
  </background>
  <description>
    <p>
    Clam AntiVirus is vulnerable to a buffer overflow in
    "libclamav/upx.c" when processing malformed UPX-packed executables. It
    can also be sent into an infinite loop in "libclamav/fsg.c" when
    processing specially-crafted FSG-packed executables.
    </p>
  </description>
  <impact type="high">
    <p>
    By sending a specially-crafted file an attacker could execute
    arbitrary code with the permissions of the user running Clam AntiVirus,
    or cause a Denial of Service.
    </p>
  </impact>
  <workaround>
    <p>
    There is no known workaround at this time.
    </p>
  </workaround>
  <resolution>
    <p>
    All Clam AntiVirus users should upgrade to the latest version:
    </p>
    <code>
    # emerge --sync
    # emerge --ask --oneshot --verbose &quot;&gt;=app-antivirus/clamav-0.87&quot;</code>
  </resolution>
  <references>
    <uri link="http://cve.mitre.org/cgi-bin/cvename.cgi?name=CAN-2005-2919">CAN-2005-2919</uri>
    <uri link="http://cve.mitre.org/cgi-bin/cvename.cgi?name=CAN-2005-2920">CAN-2005-2920</uri>
    <uri link="http://sourceforge.net/project/shownotes.php?release_id=356974">Clam AntiVirus: Release Notes</uri>
  </references>
  <metadata tag="submitter" timestamp="Sun, 18 Sep 2005 16:20:33 +0000">
    koon
  </metadata>
  <metadata tag="bugReady" timestamp="Sun, 18 Sep 2005 16:20:41 +0000">
    koon
  </metadata>
</glsa>

=== gentoo/gentoo/metadata/glsa/glsa-200904-19.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE glsa SYSTEM "http://www.gentoo.org/dtd/glsa.dtd">

<glsa id="200904-19">
  <title>LittleCMS: Multiple vulnerabilities</title>
  <synopsis>
    Multiple errors in LittleCMS allow for attacks including the remote
    execution of arbitrary code.
  </synopsis>
  <product type="ebuild">littlecms</product>
  <announced>April 19, 2009</announced>
  <revised>April 19, 2009: 01</revised>
  <bug>260269</bug>
  <bug>264604</bug>
  <access>remote</access>
  <affected>
    <package name="media-libs/lcms" auto="yes" arch="*">
      <unaffected range="ge">1.18-r1</unaffected>
      <vulnerable range="lt">1.18-r1</vulnerable>
    </package>
  </affected>
  <background>
    <p>
    LittleCMS, or short lcms, is a color management system for working with
    ICC profiles. It is used by many applications including GIMP and
    Firefox.
    </p>
  </background>
  <description>
    <p>
    RedHat reported a null-pointer dereference flaw while processing
    monochrome ICC profiles (CVE-2009-0793).
    </p>
    <p>
    Chris Evans of Google discovered the following vulnerabilities:
    </p>
    <ul>
    <li>LittleCMS contains severe memory leaks (CVE-2009-0581).</li>
    <li>LittleCMS is prone to multiple integer overflows, leading to a
    heap-based buffer overflow (CVE-2009-0723).</li>
    <li>The
    ReadSetOfCurves() function is vulnerable to stack-based buffer
    overflows when called from code paths without a bounds check on channel
    counts (CVE-2009-0733).</li>
    </ul>
  </description>
  <impact type="normal">
    <p>
    A remote attacker could entice a user or automated system to open a
    specially crafted file containing a malicious ICC profile, possibly
    resulting in the execution of arbitrary code with the privileges of the
    user running the application or memory exhaustion, leading to a Denial
    of Service condition.
    </p>
  </impact>
  <workaround>
    <p>
    There is no known workaround at this time.
    </p>
  </workaround>
  <resolution>
    <p>
    All LittleCMS users should upgrade to the latest version:
    </p>
    <code>
    # emerge --sync
    # emerge --ask --oneshot --verbose &quot;&gt;=media-libs/lcms-1.18-r1&quot;</code>
  </resolution>
  <references>
    <uri link="http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2009-0581">CVE-2009-0581</uri>
    <uri link="http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2009-0723">CVE-2009-0723</uri>
    <uri link="http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2009-0733">CVE-2009-0733</uri>
    <uri link="http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2009-0793">CVE-2009-0793</uri>
  </references>
  <metadata tag="requester" timestamp="Sun, 12 Apr 2009 15:32:46 +0000">
    rbu
  </metadata>
  <metadata tag="submitter" timestamp="Sat, 18 Apr 2009 22:41:26 +0000">
    a3li
  </metadata>
  <metadata tag="bugReady" timestamp="Sun, 19 Apr 2009 12:36:20 +0000">
    a3li
  </metadata>
</glsa>
