=== gentoo/gentoo/metadata/dtd/metadata.dtd
<!-- Metadata for a category -->
<!ELEMENT catmetadata ( (longdescription)* )>
<!ATTLIST catmetadata pkgname CDATA "">

<!-- Metadata for a package -->
<!ELEMENT pkgmetadata ( (maintainer|longdescription|slots|use|upstream)* )>
<!ATTLIST pkgmetadata pkgname CDATA "">

  <!-- One tag for each maintainer of a package, multiple allowed-->
  <!ELEMENT maintainer ( email, (description| name)* )>
  <!-- type attribute determines whether the maintainer is a person or a project.
    Unknown is added to handle <maintainer/>s in <upstream/>s. Using it (or no
    explicit type) for Gentoo maintainers is prohibited. -->
  <!ATTLIST maintainer type (person|project|unknown) "unknown">

  <!-- A long description of the package in freetext-->
  <!ELEMENT longdescription (#PCDATA|pkg|cat)* >

  <!-- A description of the packages SLOTs -->
  <!ELEMENT slots ((slot)*,subslots?) >
    <!-- A particular SLOT -->
    <!ELEMENT slot (#PCDATA)* >
      <!-- name attribute holds the name of the SLOT, for sub-SLOTS
      use the subslots element. A slot name of '*' can be used to
      indicate a single description applying to all the slots in which
      case no other <slot/> elements may be present. -->
      <!ATTLIST slot name CDATA #REQUIRED >
    <!-- The meaning of sub-SLOTs for the whole package -->
    <!ELEMENT subslots (#PCDATA)* >

  <!-- description of what this USE flag does for this package -->
  <!ELEMENT use (flag)* >
    <!ELEMENT flag (#PCDATA|pkg|cat)* >
      <!-- name attribute holds the name of the USE flag -->
      <!ATTLIST flag name CDATA #REQUIRED >

  <!-- upstream metadata information (maintainers, upstream docs,..) -->
  <!ELEMENT upstream (maintainer|changelog|doc|bugs-to|remote-id)* >
    <!-- Due to the limitation of DTD this will also allow a status
      attribute for the package maintainer element. Please note that
      the usage of the status attribute is nevertheless _only_ allowed
      in the upstream maintainer element. -->
    <!ATTLIST maintainer status (active|inactive|unknown) "unknown" >
    <!-- URL where the upstream changelog can be found -->
    <!ELEMENT changelog (#PCDATA)>
    <!-- URL where the location of the upstream documentation can be found -->
    <!ELEMENT doc (#PCDATA)>
      <!ATTLIST doc lang CDATA "en" >
    <!-- location where to report bugs
      (may also be an email address prefixed with mailto:) -->
    <!ELEMENT bugs-to (#PCDATA)>
    <!-- specify a type of package identification tracker -->
    <!ELEMENT remote-id (#PCDATA)>
      <!ATTLIST remote-id type (bitbucket|cpan|cpan-module|cpe|cran|ctan|freecode|freshmeat|gentoo|github|gitlab|gitorious|google-code|launchpad|pear|pecl|pypi|rubyforge|rubygems|sourceforge|sourceforge-jp|vim) #REQUIRED>

  <!-- category/package information for cross-linking in descriptions
    and useflag descriptions -->
  <!ELEMENT pkg (#PCDATA) >
  <!ELEMENT cat (#PCDATA) >
          
<!-- Common attributes -->

<!-- the lang attribute, specifies the language of this tag in the
  form of a ISO 639-1 language code. This is only useful for
  descriptions of various kinds. If a tag with this attribute is
  included there must be a description in the default language "en" -->
  <!ATTLIST description lang CDATA "en" >
  <!ATTLIST longdescription lang CDATA "en" >
  <!ATTLIST slots lang CDATA "en" >
  <!ATTLIST use lang CDATA "en" >

<!-- The restrict attribute, this attribute specifies restrictions on 
  the applicability of tags on versions. The format of this attribute is 
  equal to the format of DEPEND lines in ebuilds. Only package
  dependency specifications conforming to EAPI=0 syntax are allowed.
  The dependency specification may only contain references to the
  package itself and no other package.
  
  For required tags, there must be either an unrestricted version, or a 
  version that is default restricted. -->
  <!ATTLIST maintainer restrict CDATA #IMPLIED >
  <!ATTLIST longdescription restrict CDATA #IMPLIED >
  <!ATTLIST flag restrict CDATA #IMPLIED >

<!-- standard parts -->
<!-- an email address -->
<!ELEMENT email (#PCDATA) >
<!-- the name of a person (maintainer, contributor) -->
<!ELEMENT name (#PCDATA) >
<!-- A description of a maintainer or change -->
<!ELEMENT description (#PCDATA) >

=== gentoo/gentoo/dev-python/python-nss/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="person">
		<email>maksbotan@gentoo.org</email>
		<name>Maxim Koltsov</name>
	</maintainer>
	<maintainer type="project">
		<email>python@gentoo.org</email>
		<name>Python</name>
	</maintainer>
	<longdescription>
	This package provides Python bindings for Network Security Services (NSS)
	and the Netscape Portable Runtime (NSPR)
</longdescription>
</pkgmetadata>

=== gentoo/gentoo/media-sound/ncmpc/metadata.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="project">
		<email>sound@gentoo.org</email>
		<name>Gentoo Sound project</name>
	</maintainer>
	<use>
		<flag name="artist-screen">Enable artist screen</flag>
		<flag name="async-connect">Enable asynchronous connect</flag>
		<flag name="chat-screen">Enable the chat screen</flag>
		<flag name="help-screen">Enable the help screen</flag>
		<flag name="key-screen">Enable key editor screen</flag>
		<flag name="library-screen">Enable library screen</flag>
		<flag name="lyrics-screen">Enable lyrics screen</flag>
		<flag name="mouse">Enable curses getmouse support</flag>
		<flag name="outputs-screen">Enable the outputs screen</flag>
		<flag name="search-screen">Enable search screen</flag>
		<flag name="song-screen">Enable song viewer screen</flag>
		<flag name="tcp">Enable TCP support</flag>
	</use>
	<upstream>
		<remote-id type="github">MusicPlayerDaemon/ncmpc</remote-id>
	</upstream>
</pkgmetadata>

=== gentoo/gentoo/sci-mathematics/primesieve/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <maintainer type="person">
    <email>mjo@gentoo.org</email>
  </maintainer>

  <maintainer type="person" proxied="yes">
    <email>frp.bissey@gmail.com</email>
    <name>Fran√ßois Bissey</name>
  </maintainer>
  <maintainer type="project" proxied="proxy">
    <email>proxy-maint@gentoo.org</email>
    <name>Proxy Maintainers</name>
  </maintainer>

  <use>
    <flag name="executable">Build the primesieve CLI executable</flag>
  </use>

  <upstream>
    <remote-id type="github">kimwalisch/primesieve</remote-id>
  </upstream>
</pkgmetadata>

=== gentoo/gentoo/media-libs/pyilmbase/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<!--
This is the example metadata file.
The root element of this file is <pkgmetadata>. Within this element a
number of subelements are allowed, the most common being maintainer.

For a full description look at:
https://devmanual.gentoo.org/ebuild-writing/misc-files/metadata/

Before committing, please remove the comments from this file. They are
not relevant for general metadata.xml files.
-->
<pkgmetadata>
<maintainer type="person">
	<email>waebbl@gmail.com</email>
	<description>Primary maintainer</description>
</maintainer>
<longdescription>Provides python bindings for <pkg>media-libs/ilmbase</pkg></longdescription>
<use>
	<flag name="numpy">Add bindings for <pkg>dev-python/numpy</pkg> use.</flag>
</use>
</pkgmetadata>

=== gentoo/gentoo/dev-python/dreampie/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <herd>python</herd>
  <maintainer>
    <email>grozin@gentoo.org</email>
    <name>Andrey Grozin</name>
  </maintainer>
  <longdescription>
  pygtk-based python shell with autocompletion
</longdescription>
  <upstream>
    <remote-id type="pypi">dreampie</remote-id>
  </upstream>
</pkgmetadata>

=== gentoo/gentoo/x11-apps/xdpyinfo/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <maintainer type="project">
    <email>x11@gentoo.org</email>
    <name>X11</name>
  </maintainer>
  <use>
    <flag name="dmx">Builds support for Distributed Multiheaded X <pkg>x11-base/xorg-server</pkg></flag>
  </use>
  <upstream>
    <remote-id type="freedesktop-gitlab">xorg/app/xdpyinfo</remote-id>
  </upstream>
</pkgmetadata>

=== gentoo/gentoo/app-text/qtikz/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="person">
		<email>arthurzam@gentoo.org</email>
		<name>Arthur Zamarin</name>
	</maintainer>
	<upstream>
		<remote-id type="github">fhackenberger/ktikz</remote-id>
		<bugs-to>https://github.com/fhackenberger/ktikz/issues</bugs-to>
		<changelog>https://github.com/fhackenberger/ktikz/blob/master/Changelog</changelog>
	</upstream>
</pkgmetadata>

=== gentoo/gentoo/app-text/capyt/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <maintainer type="person">
    <email>juippis@gentoo.org</email>
    <name>Joonas Niilola</name>
  </maintainer>
  <stabilize-allarches/>
  <upstream>
    <remote-id type="pypi">capyt</remote-id>
    <remote-id type="github">lbatalha/capyt</remote-id>
  </upstream>
</pkgmetadata>
