=== gentoo/gentoo/metadata/dtd/metadata.dtd
<!-- Metadata for a category -->
<!ELEMENT catmetadata ( (longdescription)* )>
<!ATTLIST catmetadata pkgname CDATA "">

<!-- Metadata for a package -->
<!ELEMENT pkgmetadata ( (maintainer|longdescription|slots|use|upstream)* )>
<!ATTLIST pkgmetadata pkgname CDATA "">

  <!-- One tag for each maintainer of a package, multiple allowed-->
  <!ELEMENT maintainer ( email, (description| name)* )>
  <!-- type attribute determines whether the maintainer is a person or a project.
    Unknown is added to handle <maintainer/>s in <upstream/>s. Using it (or no
    explicit type) for Gentoo maintainers is prohibited. -->
  <!ATTLIST maintainer type (person|project|unknown) "unknown">

  <!-- A long description of the package in freetext-->
  <!ELEMENT longdescription (#PCDATA|pkg|cat)* >

  <!-- A description of the packages SLOTs -->
  <!ELEMENT slots ((slot)*,subslots?) >
    <!-- A particular SLOT -->
    <!ELEMENT slot (#PCDATA)* >
      <!-- name attribute holds the name of the SLOT, for sub-SLOTS
      use the subslots element. A slot name of '*' can be used to
      indicate a single description applying to all the slots in which
      case no other <slot/> elements may be present. -->
      <!ATTLIST slot name CDATA #REQUIRED >
    <!-- The meaning of sub-SLOTs for the whole package -->
    <!ELEMENT subslots (#PCDATA)* >

  <!-- description of what this USE flag does for this package -->
  <!ELEMENT use (flag)* >
    <!ELEMENT flag (#PCDATA|pkg|cat)* >
      <!-- name attribute holds the name of the USE flag -->
      <!ATTLIST flag name CDATA #REQUIRED >

  <!-- upstream metadata information (maintainers, upstream docs,..) -->
  <!ELEMENT upstream (maintainer|changelog|doc|bugs-to|remote-id)* >
    <!-- Due to the limitation of DTD this will also allow a status
      attribute for the package maintainer element. Please note that
      the usage of the status attribute is nevertheless _only_ allowed
      in the upstream maintainer element. -->
    <!ATTLIST maintainer status (active|inactive|unknown) "unknown" >
    <!-- URL where the upstream changelog can be found -->
    <!ELEMENT changelog (#PCDATA)>
    <!-- URL where the location of the upstream documentation can be found -->
    <!ELEMENT doc (#PCDATA)>
      <!ATTLIST doc lang CDATA "en" >
    <!-- location where to report bugs
      (may also be an email address prefixed with mailto:) -->
    <!ELEMENT bugs-to (#PCDATA)>
    <!-- specify a type of package identification tracker -->
    <!ELEMENT remote-id (#PCDATA)>
      <!ATTLIST remote-id type (bitbucket|cpan|cpan-module|cpe|cran|ctan|freecode|freshmeat|gentoo|github|gitlab|gitorious|google-code|launchpad|pear|pecl|pypi|rubyforge|rubygems|sourceforge|sourceforge-jp|vim) #REQUIRED>

  <!-- category/package information for cross-linking in descriptions
    and useflag descriptions -->
  <!ELEMENT pkg (#PCDATA) >
  <!ELEMENT cat (#PCDATA) >
          
<!-- Common attributes -->

<!-- the lang attribute, specifies the language of this tag in the
  form of a ISO 639-1 language code. This is only useful for
  descriptions of various kinds. If a tag with this attribute is
  included there must be a description in the default language "en" -->
  <!ATTLIST description lang CDATA "en" >
  <!ATTLIST longdescription lang CDATA "en" >
  <!ATTLIST slots lang CDATA "en" >
  <!ATTLIST use lang CDATA "en" >

<!-- The restrict attribute, this attribute specifies restrictions on 
  the applicability of tags on versions. The format of this attribute is 
  equal to the format of DEPEND lines in ebuilds. Only package
  dependency specifications conforming to EAPI=0 syntax are allowed.
  The dependency specification may only contain references to the
  package itself and no other package.
  
  For required tags, there must be either an unrestricted version, or a 
  version that is default restricted. -->
  <!ATTLIST maintainer restrict CDATA #IMPLIED >
  <!ATTLIST longdescription restrict CDATA #IMPLIED >
  <!ATTLIST flag restrict CDATA #IMPLIED >

<!-- standard parts -->
<!-- an email address -->
<!ELEMENT email (#PCDATA) >
<!-- the name of a person (maintainer, contributor) -->
<!ELEMENT name (#PCDATA) >
<!-- A description of a maintainer or change -->
<!ELEMENT description (#PCDATA) >

=== gentoo/gentoo/app-emulation/fs-uae/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="person">
		<email>chewi@gentoo.org</email>
		<name>James Le Cuirot</name>
	</maintainer>
	<upstream>
		<remote-id type="github">FrodeSolheim/fs-uae</remote-id>
	</upstream>
	<use>
		<flag name="fmv">Enable support for CD32 FMV (full motion video)</flag>
		<flag name="glew">Enable support for The OpenGL Extension Wrangler Library (<pkg>media-libs/glew</pkg>)</flag>
	</use>
</pkgmetadata>

=== gentoo/gentoo/app-emacs/citeproc-el/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">

<pkgmetadata>
  <maintainer type="project">
    <email>gnu-emacs@gentoo.org</email>
    <name>Gentoo GNU Emacs project</name>
  </maintainer>
  <longdescription>
    citeproc-el is an Emacs Lisp library for rendering citations and
    bibliographies in styles described in the Citation Style Language (CSL), an
    XML-based, open format to describe the formatting of bibliographic
    references (see http://citationstyles.org/ for further information on CSL).
    The library implements most of the CSL 1.0.2 specification, including such
    features as citation disambiguation, cite collapsing and subsequent author
    substitution, and passes more than 70% of the tests in the CSL Test Suite.
    In addition to the standard CSL-JSON data format, citeproc-el has
    rudimentary support for reading bibliographic data from BibTeX, biblatex
    and org-bibtex bibliographies and can produce output in several formats
    including HTML and org-mode markup (see Supported output formats for the
    full list).
  </longdescription>
  <upstream>
    <bugs-to>https://github.com/andras-simonyi/citeproc-el/issues/</bugs-to>
    <remote-id type="github">andras-simonyi/citeproc-el</remote-id>
  </upstream>
</pkgmetadata>

=== gentoo/gentoo/gnustep-base/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<catmetadata>
	<longdescription lang="en">
		The gnustep-base category contains GNUstep base packages.
	</longdescription>
	<longdescription lang="de">
		Die Kategorie gnustep-base enthält die Basispakete der
		GNUstep-Umgebung.
	</longdescription>
	<longdescription lang="es">
		La categoría gnustep-base contiene los paquetes base de GNUstep.
	</longdescription>
	<longdescription lang="ja">
		gnustep-baseカテゴリーにはGNUstepのベース・パッケージが含まれています。
	</longdescription>
	<longdescription lang="nl">
		De gnustep-base categorie bevat de basispakketten van GNUstep.
	</longdescription>
	<longdescription lang="vi">
		Nhóm gnustep-base chứa các ứng dụng GNUstep cơ bản.
	</longdescription>
	<longdescription lang="it">
		La categoria gnustep-base contiene i pacchetti base di GNUstep.
	</longdescription>
	<longdescription lang="pt">
		A categoria gnustep-base contém os pacotes de base de GNUstep.
	</longdescription>
	<longdescription lang="pl">
		Kategoria gnustep-base zawiera podstawowe pakiety GNUstep.
	</longdescription>
</catmetadata>

=== gentoo/gentoo/app-misc/nnn/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
<maintainer type="person">
    <email>foerster.florianjr@gmail.com</email>
    <name>Florian FÃ¶rster</name>
</maintainer>
    <maintainer type="project">
    <email>proxy-maint@gentoo.org</email>
    <name>Proxy Maintainers</name>
</maintainer>
<maintainer type="person">
    <email>zlogene@gentoo.org</email>
    <name>Mikle Kolyada</name>
</maintainer>
</pkgmetadata>

=== gentoo/gentoo/www-apache/mod_jk/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="person">
		<email>conikost@gentoo.org</email>
		<name>Conrad Kostecki</name>
	</maintainer>
	<maintainer type="project">
		<email>java@gentoo.org</email>
		<name>Java</name>
	</maintainer>
	<longdescription>
		Mod_JK is a connector used to connect to the Tomcat Servlet Engine,
		used with web servers such as Apache and IIS using the AJP protocol.
	</longdescription>
	<upstream>
		<remote-id type="github">apache/tomcat-connectors</remote-id>
	</upstream>
</pkgmetadata>

=== gentoo/gentoo/dev-python/setuptools-git/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <herd>python</herd>
  <maintainer>
    <email>prometheanfire@gentoo.org</email>
    <name>Matthew Thode</name>
  </maintainer>
  <longdescription lang="en">
    Setuptools revision control system plugin for Git
  </longdescription>
  <upstream>
    <remote-id type="pypi">setuptools-git</remote-id>
    <remote-id type="github">wichert/setuptools-git</remote-id>
  </upstream>
</pkgmetadata>

=== gentoo/gentoo/media-sound/guitarix/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="person">
		<email>fordfrog@gentoo.org</email>
		<name>Miroslav Å ulc</name>
	</maintainer>
	<maintainer type="person" proxied="yes">
		<email>alexander@tsoy.me</email>
		<name>Alexander Tsoy</name>
	</maintainer>
	<maintainer type="project" proxied="proxy">
		<email>proxy-maint@gentoo.org</email>
		<name>Proxy Maintainers</name>
	</maintainer>
	<use>
		<flag name="lv2">Build lv2 plugins</flag>
		<flag name="nsm">Build NSM (Non Session Manager) support</flag>
		<flag name="standalone">Build standalone application</flag>
	</use>
</pkgmetadata>

=== gentoo/gentoo/sys-cluster/neutron/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <maintainer type="person">
    <email>prometheanfire@gentoo.org</email>
    <name>Matthew Thode</name>
  </maintainer>
  <maintainer type="project">
    <email>openstack@gentoo.org</email>
    <name>Openstack</name>
  </maintainer>
  <longdescription lang="en">
    Just like OpenStack Nova provides an API to dynamically request and
	configure virtual servers, Neutron provides an API to dynamically request
	and configure virtual networks. These networks connect "interfaces" from
	other OpenStack services (e.g., vNICs from Nova VMs). The Neutron API
	supports extensions to provide advanced network capabilities
	(e.g., QoS, ACLs, network monitoring, etc).
  </longdescription>
  <use>
    <flag name="compute-only">Only install things needed on compute hosts</flag>
    <flag name="dhcp">Installs the initscripts for the neutron dhcp service</flag>
    <flag name="l3">Installs the initscripts for the neutron l3 agent service</flag>
    <flag name="metadata">Installs the initscripts for the neutron metadata agent service</flag>
    <flag name="openvswitch">Installs the initscripts for the neutron openvswitch agent service</flag>
    <flag name="linuxbridge">Installs the initscripts for the neutron linuxbridge agent service</flag>
    <flag name="server">Installs the initscripts for the neutron server service</flag>
  </use>
  <upstream>
    <remote-id type="launchpad">neutron</remote-id>
  </upstream>
</pkgmetadata>
