=== gentoo/gentoo/metadata/dtd/metadata.dtd
<!-- Metadata for a category -->
<!ELEMENT catmetadata ( (longdescription)* )>
<!ATTLIST catmetadata pkgname CDATA "">

<!-- Metadata for a package -->
<!ELEMENT pkgmetadata ( (maintainer|longdescription|slots|use|upstream)* )>
<!ATTLIST pkgmetadata pkgname CDATA "">

  <!-- One tag for each maintainer of a package, multiple allowed-->
  <!ELEMENT maintainer ( email, (description| name)* )>
  <!-- type attribute determines whether the maintainer is a person or a project.
    Unknown is added to handle <maintainer/>s in <upstream/>s. Using it (or no
    explicit type) for Gentoo maintainers is prohibited. -->
  <!ATTLIST maintainer type (person|project|unknown) "unknown">

  <!-- A long description of the package in freetext-->
  <!ELEMENT longdescription (#PCDATA|pkg|cat)* >

  <!-- A description of the packages SLOTs -->
  <!ELEMENT slots ((slot)*,subslots?) >
    <!-- A particular SLOT -->
    <!ELEMENT slot (#PCDATA)* >
      <!-- name attribute holds the name of the SLOT, for sub-SLOTS
      use the subslots element. A slot name of '*' can be used to
      indicate a single description applying to all the slots in which
      case no other <slot/> elements may be present. -->
      <!ATTLIST slot name CDATA #REQUIRED >
    <!-- The meaning of sub-SLOTs for the whole package -->
    <!ELEMENT subslots (#PCDATA)* >

  <!-- description of what this USE flag does for this package -->
  <!ELEMENT use (flag)* >
    <!ELEMENT flag (#PCDATA|pkg|cat)* >
      <!-- name attribute holds the name of the USE flag -->
      <!ATTLIST flag name CDATA #REQUIRED >

  <!-- upstream metadata information (maintainers, upstream docs,..) -->
  <!ELEMENT upstream (maintainer|changelog|doc|bugs-to|remote-id)* >
    <!-- Due to the limitation of DTD this will also allow a status
      attribute for the package maintainer element. Please note that
      the usage of the status attribute is nevertheless _only_ allowed
      in the upstream maintainer element. -->
    <!ATTLIST maintainer status (active|inactive|unknown) "unknown" >
    <!-- URL where the upstream changelog can be found -->
    <!ELEMENT changelog (#PCDATA)>
    <!-- URL where the location of the upstream documentation can be found -->
    <!ELEMENT doc (#PCDATA)>
      <!ATTLIST doc lang CDATA "en" >
    <!-- location where to report bugs
      (may also be an email address prefixed with mailto:) -->
    <!ELEMENT bugs-to (#PCDATA)>
    <!-- specify a type of package identification tracker -->
    <!ELEMENT remote-id (#PCDATA)>
      <!ATTLIST remote-id type (bitbucket|cpan|cpan-module|cpe|cran|ctan|freecode|freshmeat|gentoo|github|gitlab|gitorious|google-code|launchpad|pear|pecl|pypi|rubyforge|rubygems|sourceforge|sourceforge-jp|vim) #REQUIRED>

  <!-- category/package information for cross-linking in descriptions
    and useflag descriptions -->
  <!ELEMENT pkg (#PCDATA) >
  <!ELEMENT cat (#PCDATA) >
          
<!-- Common attributes -->

<!-- the lang attribute, specifies the language of this tag in the
  form of a ISO 639-1 language code. This is only useful for
  descriptions of various kinds. If a tag with this attribute is
  included there must be a description in the default language "en" -->
  <!ATTLIST description lang CDATA "en" >
  <!ATTLIST longdescription lang CDATA "en" >
  <!ATTLIST slots lang CDATA "en" >
  <!ATTLIST use lang CDATA "en" >

<!-- The restrict attribute, this attribute specifies restrictions on 
  the applicability of tags on versions. The format of this attribute is 
  equal to the format of DEPEND lines in ebuilds. Only package
  dependency specifications conforming to EAPI=0 syntax are allowed.
  The dependency specification may only contain references to the
  package itself and no other package.
  
  For required tags, there must be either an unrestricted version, or a 
  version that is default restricted. -->
  <!ATTLIST maintainer restrict CDATA #IMPLIED >
  <!ATTLIST longdescription restrict CDATA #IMPLIED >
  <!ATTLIST flag restrict CDATA #IMPLIED >

<!-- standard parts -->
<!-- an email address -->
<!ELEMENT email (#PCDATA) >
<!-- the name of a person (maintainer, contributor) -->
<!ELEMENT name (#PCDATA) >
<!-- A description of a maintainer or change -->
<!ELEMENT description (#PCDATA) >

=== gentoo/gentoo/app-emacs/pdf-tools/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">

<pkgmetadata>
  <maintainer type="project">
    <email>gnu-emacs@gentoo.org</email>
    <name>Gentoo GNU Emacs project</name>
  </maintainer>
  <longdescription>
    PDF Tools is, among other things, a replacement of DocView for PDF files.
    The key difference is that pages are not pre-rendered by e.g. ghostscript
    and stored in the file-system, but rather created on-demand and stored in
    memory. This rendering is performed by a special library named, for
    whatever reason, poppler, running inside a server program. This program is
    called epdfinfo and its job is to successively read requests from Emacs and
    produce the proper results, i.e. the PNG image of a PDF page. Actually,
    displaying PDF files is just one part of pdf-tools. Since poppler can
    provide us with all kinds of information about a document and is also able
    to modify it, there is a lot more we can do with it.
  </longdescription>
  <upstream>
    <bugs-to>https://github.com/vedang/pdf-tools/issues/</bugs-to>
    <remote-id type="github">vedang/pdf-tools</remote-id>
  </upstream>
</pkgmetadata>

=== gentoo/gentoo/games-util/gamemode/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="person">
		<email>hurikhan77+bgo@gmail.com</email>
		<name>Kai Krakow</name>
	</maintainer>
	<maintainer type="project">
		<email>proxy-maint@gentoo.org</email>
		<name>Proxy Maintainers</name>
	</maintainer>
	<upstream>
		<bugs-to>https://github.com/FeralInteractive/gamemode/issues</bugs-to>
		<remote-id type="github">FeralInteractive/gamemode</remote-id>
	</upstream>
</pkgmetadata>

=== gentoo/gentoo/dev-python/awkward-cpp/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="person">
		<email>apn-pucky@gentoo.org</email>
		<name>Alexander Puck Neuwirth</name>
	</maintainer>
	<maintainer type="project">
		<email>sci@gentoo.org</email>
		<name>Gentoo Science Project</name>
	</maintainer>
	<maintainer type="project">
		<email>python@gentoo.org</email>
		<name>Python</name>
	</maintainer>


	<longdescription lang="en">
	awkward-cpp provides precompiled routines for the awkward package. It is not useful on its own, only as a dependency for awkward .
	</longdescription>
	<upstream>
		<remote-id type="pypi">awkward-cpp</remote-id>
		<remote-id type="github">scikit-hep/awkward</remote-id>
	</upstream>
</pkgmetadata>

=== gentoo/gentoo/dev-python/snowballstemmer/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="project">
		<email>python@gentoo.org</email>
		<name>Python</name>
	</maintainer>
	<stabilize-allarches/>
	<upstream>
		<remote-id type="pypi">snowballstemmer</remote-id>
		<remote-id type="github">snowballstem/snowball</remote-id>
	</upstream>
</pkgmetadata>

=== gentoo/gentoo/sys-apps/pkgcore/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="project">
		<email>pkgcore@gentoo.org</email>
		<name>Pkgcore</name>
	</maintainer>
	<stabilize-allarches/>
	<upstream>
		<remote-id type="github">pkgcore/pkgcore</remote-id>
		<remote-id type="pypi">pkgcore</remote-id>
	</upstream>
</pkgmetadata>

=== gentoo/gentoo/app-crypt/gcr/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <maintainer type="project">
    <email>gnome@gentoo.org</email>
    <name>Gentoo GNOME Desktop</name>
  </maintainer>
  <upstream>
    <changelog>https://gitlab.gnome.org/GNOME/gcr/-/blob/main/NEWS</changelog>
    <doc>https://gnome.pages.gitlab.gnome.org/gcr/gcr-4/</doc>
    <remote-id type="gnome-gitlab">GNOME/gcr</remote-id>
  </upstream>
</pkgmetadata>

=== gentoo/gentoo/dev-perl/Set-Crontab/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <maintainer type="person">
    <email>dev-zero@gentoo.org</email>
    <name>Tiziano MÃ¼ller</name>
  </maintainer>
  <maintainer type="project">
    <email>perl@gentoo.org</email>
    <name>Gentoo Perl Project</name>
  </maintainer>
  <upstream>
    <remote-id type="cpan">Set-Crontab</remote-id>
    <remote-id type="cpan-module">Set::Crontab</remote-id>
  </upstream>
</pkgmetadata>

=== gentoo/gentoo/virtual/wine/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="project">
		<email>wine@gentoo.org</email>
		<name>Wine</name>
	</maintainer>
	<use>
		<flag name="proton">Enable Valve Software's fork of Wine</flag>
		<flag name="staging">Enable Wine-Staging's Patchset</flag>
	</use>
	<stabilize-allarches/>
	<longdescription lang="en">
		Allows for any variant of Wine, regardless of slotting to fulfill the dependencies
		traditionally fulfilled by the non-slotted, pre-variant, app-emulation/wine.
	</longdescription>
</pkgmetadata>
